// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kweaver-ai/idrm-go-common/rest/configuration_center (interfaces: Driven)
//
// Generated by this command:
//
//	mockgen -destination=configuration_center.go -package=mock -typed -write_generate_directive github.com/kweaver-ai/idrm-go-common/rest/configuration_center Driven
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	access_control "github.com/kweaver-ai/idrm-go-common/access_control"
	base "github.com/kweaver-ai/idrm-go-common/rest/base"
	configuration_center "github.com/kweaver-ai/idrm-go-common/rest/configuration_center"
	gomock "go.uber.org/mock/gomock"
)

//go:generate mockgen -destination=configuration_center.go -package=mock -typed -write_generate_directive github.com/kweaver-ai/idrm-go-common/rest/configuration_center Driven

// MockDriven is a mock of Driven interface.
type MockDriven struct {
	ctrl     *gomock.Controller
	recorder *MockDrivenMockRecorder
	isgomock struct{}
}

// MockDrivenMockRecorder is the mock recorder for MockDriven.
type MockDrivenMockRecorder struct {
	mock *MockDriven
}

// NewMockDriven creates a new mock instance.
func NewMockDriven(ctrl *gomock.Controller) *MockDriven {
	mock := &MockDriven{ctrl: ctrl}
	mock.recorder = &MockDrivenMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriven) EXPECT() *MockDrivenMockRecorder {
	return m.recorder
}

// BatchCheckNotExistTypeKey mocks base method.
func (m *MockDriven) BatchCheckNotExistTypeKey(ctx context.Context, req configuration_center.CheckDictTypeKeyReq) (*[]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCheckNotExistTypeKey", ctx, req)
	ret0, _ := ret[0].(*[]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchCheckNotExistTypeKey indicates an expected call of BatchCheckNotExistTypeKey.
func (mr *MockDrivenMockRecorder) BatchCheckNotExistTypeKey(ctx, req any) *MockDrivenBatchCheckNotExistTypeKeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCheckNotExistTypeKey", reflect.TypeOf((*MockDriven)(nil).BatchCheckNotExistTypeKey), ctx, req)
	return &MockDrivenBatchCheckNotExistTypeKeyCall{Call: call}
}

// MockDrivenBatchCheckNotExistTypeKeyCall wrap *gomock.Call
type MockDrivenBatchCheckNotExistTypeKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenBatchCheckNotExistTypeKeyCall) Return(arg0 *[]string, arg1 error) *MockDrivenBatchCheckNotExistTypeKeyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenBatchCheckNotExistTypeKeyCall) Do(f func(context.Context, configuration_center.CheckDictTypeKeyReq) (*[]string, error)) *MockDrivenBatchCheckNotExistTypeKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenBatchCheckNotExistTypeKeyCall) DoAndReturn(f func(context.Context, configuration_center.CheckDictTypeKeyReq) (*[]string, error)) *MockDrivenBatchCheckNotExistTypeKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteFile mocks base method.
func (m *MockDriven) DeleteFile(ctx context.Context, deptID, ossID, fileName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", ctx, deptID, ossID, fileName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockDrivenMockRecorder) DeleteFile(ctx, deptID, ossID, fileName any) *MockDrivenDeleteFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockDriven)(nil).DeleteFile), ctx, deptID, ossID, fileName)
	return &MockDrivenDeleteFileCall{Call: call}
}

// MockDrivenDeleteFileCall wrap *gomock.Call
type MockDrivenDeleteFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenDeleteFileCall) Return(err error) *MockDrivenDeleteFileCall {
	c.Call = c.Call.Return(err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenDeleteFileCall) Do(f func(context.Context, string, string, string) error) *MockDrivenDeleteFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenDeleteFileCall) DoAndReturn(f func(context.Context, string, string, string) error) *MockDrivenDeleteFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteProcessBindByAuditType mocks base method.
func (m *MockDriven) DeleteProcessBindByAuditType(ctx context.Context, auditType *configuration_center.DeleteProcessBindByAuditTypeReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProcessBindByAuditType", ctx, auditType)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProcessBindByAuditType indicates an expected call of DeleteProcessBindByAuditType.
func (mr *MockDrivenMockRecorder) DeleteProcessBindByAuditType(ctx, auditType any) *MockDrivenDeleteProcessBindByAuditTypeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProcessBindByAuditType", reflect.TypeOf((*MockDriven)(nil).DeleteProcessBindByAuditType), ctx, auditType)
	return &MockDrivenDeleteProcessBindByAuditTypeCall{Call: call}
}

// MockDrivenDeleteProcessBindByAuditTypeCall wrap *gomock.Call
type MockDrivenDeleteProcessBindByAuditTypeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenDeleteProcessBindByAuditTypeCall) Return(err error) *MockDrivenDeleteProcessBindByAuditTypeCall {
	c.Call = c.Call.Return(err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenDeleteProcessBindByAuditTypeCall) Do(f func(context.Context, *configuration_center.DeleteProcessBindByAuditTypeReq) error) *MockDrivenDeleteProcessBindByAuditTypeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenDeleteProcessBindByAuditTypeCall) DoAndReturn(f func(context.Context, *configuration_center.DeleteProcessBindByAuditTypeReq) error) *MockDrivenDeleteProcessBindByAuditTypeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Generate mocks base method.
func (m *MockDriven) Generate(ctx context.Context, id string, count int) (*configuration_center.CodeList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", ctx, id, count)
	ret0, _ := ret[0].(*configuration_center.CodeList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockDrivenMockRecorder) Generate(ctx, id, count any) *MockDrivenGenerateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockDriven)(nil).Generate), ctx, id, count)
	return &MockDrivenGenerateCall{Call: call}
}

// MockDrivenGenerateCall wrap *gomock.Call
type MockDrivenGenerateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGenerateCall) Return(arg0 *configuration_center.CodeList, arg1 error) *MockDrivenGenerateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGenerateCall) Do(f func(context.Context, string, int) (*configuration_center.CodeList, error)) *MockDrivenGenerateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGenerateCall) DoAndReturn(f func(context.Context, string, int) (*configuration_center.CodeList, error)) *MockDrivenGenerateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetAllDataSources mocks base method.
func (m *MockDriven) GetAllDataSources(ctx context.Context) ([]*configuration_center.DataSources, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllDataSources", ctx)
	ret0, _ := ret[0].([]*configuration_center.DataSources)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllDataSources indicates an expected call of GetAllDataSources.
func (mr *MockDrivenMockRecorder) GetAllDataSources(ctx any) *MockDrivenGetAllDataSourcesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllDataSources", reflect.TypeOf((*MockDriven)(nil).GetAllDataSources), ctx)
	return &MockDrivenGetAllDataSourcesCall{Call: call}
}

// MockDrivenGetAllDataSourcesCall wrap *gomock.Call
type MockDrivenGetAllDataSourcesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetAllDataSourcesCall) Return(arg0 []*configuration_center.DataSources, arg1 error) *MockDrivenGetAllDataSourcesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetAllDataSourcesCall) Do(f func(context.Context) ([]*configuration_center.DataSources, error)) *MockDrivenGetAllDataSourcesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetAllDataSourcesCall) DoAndReturn(f func(context.Context) ([]*configuration_center.DataSources, error)) *MockDrivenGetAllDataSourcesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetApplication mocks base method.
func (m *MockDriven) GetApplication(ctx context.Context, id string) (*configuration_center.Apps, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApplication", ctx, id)
	ret0, _ := ret[0].(*configuration_center.Apps)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApplication indicates an expected call of GetApplication.
func (mr *MockDrivenMockRecorder) GetApplication(ctx, id any) *MockDrivenGetApplicationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApplication", reflect.TypeOf((*MockDriven)(nil).GetApplication), ctx, id)
	return &MockDrivenGetApplicationCall{Call: call}
}

// MockDrivenGetApplicationCall wrap *gomock.Call
type MockDrivenGetApplicationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetApplicationCall) Return(arg0 *configuration_center.Apps, arg1 error) *MockDrivenGetApplicationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetApplicationCall) Do(f func(context.Context, string) (*configuration_center.Apps, error)) *MockDrivenGetApplicationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetApplicationCall) DoAndReturn(f func(context.Context, string) (*configuration_center.Apps, error)) *MockDrivenGetApplicationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetAppsByAccountId mocks base method.
func (m *MockDriven) GetAppsByAccountId(ctx context.Context, id string) (*configuration_center.Apps, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppsByAccountId", ctx, id)
	ret0, _ := ret[0].(*configuration_center.Apps)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppsByAccountId indicates an expected call of GetAppsByAccountId.
func (mr *MockDrivenMockRecorder) GetAppsByAccountId(ctx, id any) *MockDrivenGetAppsByAccountIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppsByAccountId", reflect.TypeOf((*MockDriven)(nil).GetAppsByAccountId), ctx, id)
	return &MockDrivenGetAppsByAccountIdCall{Call: call}
}

// MockDrivenGetAppsByAccountIdCall wrap *gomock.Call
type MockDrivenGetAppsByAccountIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetAppsByAccountIdCall) Return(arg0 *configuration_center.Apps, arg1 error) *MockDrivenGetAppsByAccountIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetAppsByAccountIdCall) Do(f func(context.Context, string) (*configuration_center.Apps, error)) *MockDrivenGetAppsByAccountIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetAppsByAccountIdCall) DoAndReturn(f func(context.Context, string) (*configuration_center.Apps, error)) *MockDrivenGetAppsByAccountIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetCheckUserPermission mocks base method.
func (m *MockDriven) GetCheckUserPermission(ctx context.Context, permissionId, uid string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCheckUserPermission", ctx, permissionId, uid)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCheckUserPermission indicates an expected call of GetCheckUserPermission.
func (mr *MockDrivenMockRecorder) GetCheckUserPermission(ctx, permissionId, uid any) *MockDrivenGetCheckUserPermissionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCheckUserPermission", reflect.TypeOf((*MockDriven)(nil).GetCheckUserPermission), ctx, permissionId, uid)
	return &MockDrivenGetCheckUserPermissionCall{Call: call}
}

// MockDrivenGetCheckUserPermissionCall wrap *gomock.Call
type MockDrivenGetCheckUserPermissionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetCheckUserPermissionCall) Return(arg0 bool, arg1 error) *MockDrivenGetCheckUserPermissionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetCheckUserPermissionCall) Do(f func(context.Context, string, string) (bool, error)) *MockDrivenGetCheckUserPermissionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetCheckUserPermissionCall) DoAndReturn(f func(context.Context, string, string) (bool, error)) *MockDrivenGetCheckUserPermissionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetChildDepartments mocks base method.
func (m *MockDriven) GetChildDepartments(ctx context.Context, orgCode string) (*base.PageResult[configuration_center.DepartmentObject], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChildDepartments", ctx, orgCode)
	ret0, _ := ret[0].(*base.PageResult[configuration_center.DepartmentObject])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChildDepartments indicates an expected call of GetChildDepartments.
func (mr *MockDrivenMockRecorder) GetChildDepartments(ctx, orgCode any) *MockDrivenGetChildDepartmentsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChildDepartments", reflect.TypeOf((*MockDriven)(nil).GetChildDepartments), ctx, orgCode)
	return &MockDrivenGetChildDepartmentsCall{Call: call}
}

// MockDrivenGetChildDepartmentsCall wrap *gomock.Call
type MockDrivenGetChildDepartmentsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetChildDepartmentsCall) Return(arg0 *base.PageResult[configuration_center.DepartmentObject], arg1 error) *MockDrivenGetChildDepartmentsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetChildDepartmentsCall) Do(f func(context.Context, string) (*base.PageResult[configuration_center.DepartmentObject], error)) *MockDrivenGetChildDepartmentsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetChildDepartmentsCall) DoAndReturn(f func(context.Context, string) (*base.PageResult[configuration_center.DepartmentObject], error)) *MockDrivenGetChildDepartmentsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetDataSourcePrecision mocks base method.
func (m *MockDriven) GetDataSourcePrecision(ctx context.Context, ids []string) ([]*configuration_center.DataSourcesPrecision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataSourcePrecision", ctx, ids)
	ret0, _ := ret[0].([]*configuration_center.DataSourcesPrecision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataSourcePrecision indicates an expected call of GetDataSourcePrecision.
func (mr *MockDrivenMockRecorder) GetDataSourcePrecision(ctx, ids any) *MockDrivenGetDataSourcePrecisionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataSourcePrecision", reflect.TypeOf((*MockDriven)(nil).GetDataSourcePrecision), ctx, ids)
	return &MockDrivenGetDataSourcePrecisionCall{Call: call}
}

// MockDrivenGetDataSourcePrecisionCall wrap *gomock.Call
type MockDrivenGetDataSourcePrecisionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetDataSourcePrecisionCall) Return(arg0 []*configuration_center.DataSourcesPrecision, arg1 error) *MockDrivenGetDataSourcePrecisionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetDataSourcePrecisionCall) Do(f func(context.Context, []string) ([]*configuration_center.DataSourcesPrecision, error)) *MockDrivenGetDataSourcePrecisionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetDataSourcePrecisionCall) DoAndReturn(f func(context.Context, []string) ([]*configuration_center.DataSourcesPrecision, error)) *MockDrivenGetDataSourcePrecisionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetDataSourcesByType mocks base method.
func (m *MockDriven) GetDataSourcesByType(ctx context.Context, dataBaseType string) ([]*configuration_center.DataSourcePage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataSourcesByType", ctx, dataBaseType)
	ret0, _ := ret[0].([]*configuration_center.DataSourcePage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataSourcesByType indicates an expected call of GetDataSourcesByType.
func (mr *MockDrivenMockRecorder) GetDataSourcesByType(ctx, dataBaseType any) *MockDrivenGetDataSourcesByTypeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataSourcesByType", reflect.TypeOf((*MockDriven)(nil).GetDataSourcesByType), ctx, dataBaseType)
	return &MockDrivenGetDataSourcesByTypeCall{Call: call}
}

// MockDrivenGetDataSourcesByTypeCall wrap *gomock.Call
type MockDrivenGetDataSourcesByTypeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetDataSourcesByTypeCall) Return(arg0 []*configuration_center.DataSourcePage, arg1 error) *MockDrivenGetDataSourcesByTypeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetDataSourcesByTypeCall) Do(f func(context.Context, string) ([]*configuration_center.DataSourcePage, error)) *MockDrivenGetDataSourcesByTypeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetDataSourcesByTypeCall) DoAndReturn(f func(context.Context, string) ([]*configuration_center.DataSourcePage, error)) *MockDrivenGetDataSourcesByTypeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetDatasourcesByHuaAoID mocks base method.
func (m *MockDriven) GetDatasourcesByHuaAoID(ctx context.Context, huaAoID string) (*configuration_center.DataSourcePage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatasourcesByHuaAoID", ctx, huaAoID)
	ret0, _ := ret[0].(*configuration_center.DataSourcePage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDatasourcesByHuaAoID indicates an expected call of GetDatasourcesByHuaAoID.
func (mr *MockDrivenMockRecorder) GetDatasourcesByHuaAoID(ctx, huaAoID any) *MockDrivenGetDatasourcesByHuaAoIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatasourcesByHuaAoID", reflect.TypeOf((*MockDriven)(nil).GetDatasourcesByHuaAoID), ctx, huaAoID)
	return &MockDrivenGetDatasourcesByHuaAoIDCall{Call: call}
}

// MockDrivenGetDatasourcesByHuaAoIDCall wrap *gomock.Call
type MockDrivenGetDatasourcesByHuaAoIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetDatasourcesByHuaAoIDCall) Return(arg0 *configuration_center.DataSourcePage, arg1 error) *MockDrivenGetDatasourcesByHuaAoIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetDatasourcesByHuaAoIDCall) Do(f func(context.Context, string) (*configuration_center.DataSourcePage, error)) *MockDrivenGetDatasourcesByHuaAoIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetDatasourcesByHuaAoIDCall) DoAndReturn(f func(context.Context, string) (*configuration_center.DataSourcePage, error)) *MockDrivenGetDatasourcesByHuaAoIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetDepartmentByPath mocks base method.
func (m *MockDriven) GetDepartmentByPath(ctx context.Context, paths *configuration_center.GetDepartmentByPathReq) (*configuration_center.GetDepartmentByPathRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDepartmentByPath", ctx, paths)
	ret0, _ := ret[0].(*configuration_center.GetDepartmentByPathRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDepartmentByPath indicates an expected call of GetDepartmentByPath.
func (mr *MockDrivenMockRecorder) GetDepartmentByPath(ctx, paths any) *MockDrivenGetDepartmentByPathCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDepartmentByPath", reflect.TypeOf((*MockDriven)(nil).GetDepartmentByPath), ctx, paths)
	return &MockDrivenGetDepartmentByPathCall{Call: call}
}

// MockDrivenGetDepartmentByPathCall wrap *gomock.Call
type MockDrivenGetDepartmentByPathCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetDepartmentByPathCall) Return(res *configuration_center.GetDepartmentByPathRes, err error) *MockDrivenGetDepartmentByPathCall {
	c.Call = c.Call.Return(res, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetDepartmentByPathCall) Do(f func(context.Context, *configuration_center.GetDepartmentByPathReq) (*configuration_center.GetDepartmentByPathRes, error)) *MockDrivenGetDepartmentByPathCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetDepartmentByPathCall) DoAndReturn(f func(context.Context, *configuration_center.GetDepartmentByPathReq) (*configuration_center.GetDepartmentByPathRes, error)) *MockDrivenGetDepartmentByPathCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetDepartmentList mocks base method.
func (m *MockDriven) GetDepartmentList(ctx context.Context, reqParam configuration_center.QueryPageReqParam) (*configuration_center.QueryPageReapParam, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDepartmentList", ctx, reqParam)
	ret0, _ := ret[0].(*configuration_center.QueryPageReapParam)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDepartmentList indicates an expected call of GetDepartmentList.
func (mr *MockDrivenMockRecorder) GetDepartmentList(ctx, reqParam any) *MockDrivenGetDepartmentListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDepartmentList", reflect.TypeOf((*MockDriven)(nil).GetDepartmentList), ctx, reqParam)
	return &MockDrivenGetDepartmentListCall{Call: call}
}

// MockDrivenGetDepartmentListCall wrap *gomock.Call
type MockDrivenGetDepartmentListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetDepartmentListCall) Return(res *configuration_center.QueryPageReapParam, err error) *MockDrivenGetDepartmentListCall {
	c.Call = c.Call.Return(res, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetDepartmentListCall) Do(f func(context.Context, configuration_center.QueryPageReqParam) (*configuration_center.QueryPageReapParam, error)) *MockDrivenGetDepartmentListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetDepartmentListCall) DoAndReturn(f func(context.Context, configuration_center.QueryPageReqParam) (*configuration_center.QueryPageReapParam, error)) *MockDrivenGetDepartmentListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetDepartmentListInternal mocks base method.
func (m *MockDriven) GetDepartmentListInternal(ctx context.Context, reqParam configuration_center.QueryPageReqParam) (*configuration_center.QueryPageReapParam, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDepartmentListInternal", ctx, reqParam)
	ret0, _ := ret[0].(*configuration_center.QueryPageReapParam)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDepartmentListInternal indicates an expected call of GetDepartmentListInternal.
func (mr *MockDrivenMockRecorder) GetDepartmentListInternal(ctx, reqParam any) *MockDrivenGetDepartmentListInternalCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDepartmentListInternal", reflect.TypeOf((*MockDriven)(nil).GetDepartmentListInternal), ctx, reqParam)
	return &MockDrivenGetDepartmentListInternalCall{Call: call}
}

// MockDrivenGetDepartmentListInternalCall wrap *gomock.Call
type MockDrivenGetDepartmentListInternalCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetDepartmentListInternalCall) Return(res *configuration_center.QueryPageReapParam, err error) *MockDrivenGetDepartmentListInternalCall {
	c.Call = c.Call.Return(res, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetDepartmentListInternalCall) Do(f func(context.Context, configuration_center.QueryPageReqParam) (*configuration_center.QueryPageReapParam, error)) *MockDrivenGetDepartmentListInternalCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetDepartmentListInternalCall) DoAndReturn(f func(context.Context, configuration_center.QueryPageReqParam) (*configuration_center.QueryPageReapParam, error)) *MockDrivenGetDepartmentListInternalCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetDepartmentPrecision mocks base method.
func (m *MockDriven) GetDepartmentPrecision(ctx context.Context, ids []string) (*configuration_center.GetDepartmentPrecisionRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDepartmentPrecision", ctx, ids)
	ret0, _ := ret[0].(*configuration_center.GetDepartmentPrecisionRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDepartmentPrecision indicates an expected call of GetDepartmentPrecision.
func (mr *MockDrivenMockRecorder) GetDepartmentPrecision(ctx, ids any) *MockDrivenGetDepartmentPrecisionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDepartmentPrecision", reflect.TypeOf((*MockDriven)(nil).GetDepartmentPrecision), ctx, ids)
	return &MockDrivenGetDepartmentPrecisionCall{Call: call}
}

// MockDrivenGetDepartmentPrecisionCall wrap *gomock.Call
type MockDrivenGetDepartmentPrecisionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetDepartmentPrecisionCall) Return(res *configuration_center.GetDepartmentPrecisionRes, err error) *MockDrivenGetDepartmentPrecisionCall {
	c.Call = c.Call.Return(res, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetDepartmentPrecisionCall) Do(f func(context.Context, []string) (*configuration_center.GetDepartmentPrecisionRes, error)) *MockDrivenGetDepartmentPrecisionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetDepartmentPrecisionCall) DoAndReturn(f func(context.Context, []string) (*configuration_center.GetDepartmentPrecisionRes, error)) *MockDrivenGetDepartmentPrecisionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetDepartments mocks base method.
func (m *MockDriven) GetDepartments(ctx context.Context, orgCodes []string) ([]*configuration_center.DepartmentObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDepartments", ctx, orgCodes)
	ret0, _ := ret[0].([]*configuration_center.DepartmentObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDepartments indicates an expected call of GetDepartments.
func (mr *MockDrivenMockRecorder) GetDepartments(ctx, orgCodes any) *MockDrivenGetDepartmentsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDepartments", reflect.TypeOf((*MockDriven)(nil).GetDepartments), ctx, orgCodes)
	return &MockDrivenGetDepartmentsCall{Call: call}
}

// MockDrivenGetDepartmentsCall wrap *gomock.Call
type MockDrivenGetDepartmentsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetDepartmentsCall) Return(arg0 []*configuration_center.DepartmentObject, arg1 error) *MockDrivenGetDepartmentsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetDepartmentsCall) Do(f func(context.Context, []string) ([]*configuration_center.DepartmentObject, error)) *MockDrivenGetDepartmentsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetDepartmentsCall) DoAndReturn(f func(context.Context, []string) ([]*configuration_center.DepartmentObject, error)) *MockDrivenGetDepartmentsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetDepartmentsByCode mocks base method.
func (m *MockDriven) GetDepartmentsByCode(ctx context.Context, orgCode string) (*configuration_center.DepartmentObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDepartmentsByCode", ctx, orgCode)
	ret0, _ := ret[0].(*configuration_center.DepartmentObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDepartmentsByCode indicates an expected call of GetDepartmentsByCode.
func (mr *MockDrivenMockRecorder) GetDepartmentsByCode(ctx, orgCode any) *MockDrivenGetDepartmentsByCodeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDepartmentsByCode", reflect.TypeOf((*MockDriven)(nil).GetDepartmentsByCode), ctx, orgCode)
	return &MockDrivenGetDepartmentsByCodeCall{Call: call}
}

// MockDrivenGetDepartmentsByCodeCall wrap *gomock.Call
type MockDrivenGetDepartmentsByCodeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetDepartmentsByCodeCall) Return(arg0 *configuration_center.DepartmentObject, arg1 error) *MockDrivenGetDepartmentsByCodeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetDepartmentsByCodeCall) Do(f func(context.Context, string) (*configuration_center.DepartmentObject, error)) *MockDrivenGetDepartmentsByCodeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetDepartmentsByCodeCall) DoAndReturn(f func(context.Context, string) (*configuration_center.DepartmentObject, error)) *MockDrivenGetDepartmentsByCodeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetDepartmentsByCodeInternal mocks base method.
func (m *MockDriven) GetDepartmentsByCodeInternal(ctx context.Context, orgCode string) (*configuration_center.DepartmentObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDepartmentsByCodeInternal", ctx, orgCode)
	ret0, _ := ret[0].(*configuration_center.DepartmentObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDepartmentsByCodeInternal indicates an expected call of GetDepartmentsByCodeInternal.
func (mr *MockDrivenMockRecorder) GetDepartmentsByCodeInternal(ctx, orgCode any) *MockDrivenGetDepartmentsByCodeInternalCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDepartmentsByCodeInternal", reflect.TypeOf((*MockDriven)(nil).GetDepartmentsByCodeInternal), ctx, orgCode)
	return &MockDrivenGetDepartmentsByCodeInternalCall{Call: call}
}

// MockDrivenGetDepartmentsByCodeInternalCall wrap *gomock.Call
type MockDrivenGetDepartmentsByCodeInternalCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetDepartmentsByCodeInternalCall) Return(arg0 *configuration_center.DepartmentObject, arg1 error) *MockDrivenGetDepartmentsByCodeInternalCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetDepartmentsByCodeInternalCall) Do(f func(context.Context, string) (*configuration_center.DepartmentObject, error)) *MockDrivenGetDepartmentsByCodeInternalCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetDepartmentsByCodeInternalCall) DoAndReturn(f func(context.Context, string) (*configuration_center.DepartmentObject, error)) *MockDrivenGetDepartmentsByCodeInternalCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetDepartmentsByUserID mocks base method.
func (m *MockDriven) GetDepartmentsByUserID(ctx context.Context, userID string) ([]*configuration_center.DepartmentObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDepartmentsByUserID", ctx, userID)
	ret0, _ := ret[0].([]*configuration_center.DepartmentObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDepartmentsByUserID indicates an expected call of GetDepartmentsByUserID.
func (mr *MockDrivenMockRecorder) GetDepartmentsByUserID(ctx, userID any) *MockDrivenGetDepartmentsByUserIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDepartmentsByUserID", reflect.TypeOf((*MockDriven)(nil).GetDepartmentsByUserID), ctx, userID)
	return &MockDrivenGetDepartmentsByUserIDCall{Call: call}
}

// MockDrivenGetDepartmentsByUserIDCall wrap *gomock.Call
type MockDrivenGetDepartmentsByUserIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetDepartmentsByUserIDCall) Return(arg0 []*configuration_center.DepartmentObject, arg1 error) *MockDrivenGetDepartmentsByUserIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetDepartmentsByUserIDCall) Do(f func(context.Context, string) ([]*configuration_center.DepartmentObject, error)) *MockDrivenGetDepartmentsByUserIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetDepartmentsByUserIDCall) DoAndReturn(f func(context.Context, string) ([]*configuration_center.DepartmentObject, error)) *MockDrivenGetDepartmentsByUserIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetDictItemPage mocks base method.
func (m *MockDriven) GetDictItemPage(ctx context.Context, req *configuration_center.GetDictItemPageReq) (*configuration_center.GetDictItemPageRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDictItemPage", ctx, req)
	ret0, _ := ret[0].(*configuration_center.GetDictItemPageRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDictItemPage indicates an expected call of GetDictItemPage.
func (mr *MockDrivenMockRecorder) GetDictItemPage(ctx, req any) *MockDrivenGetDictItemPageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDictItemPage", reflect.TypeOf((*MockDriven)(nil).GetDictItemPage), ctx, req)
	return &MockDrivenGetDictItemPageCall{Call: call}
}

// MockDrivenGetDictItemPageCall wrap *gomock.Call
type MockDrivenGetDictItemPageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetDictItemPageCall) Return(arg0 *configuration_center.GetDictItemPageRes, arg1 error) *MockDrivenGetDictItemPageCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetDictItemPageCall) Do(f func(context.Context, *configuration_center.GetDictItemPageReq) (*configuration_center.GetDictItemPageRes, error)) *MockDrivenGetDictItemPageCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetDictItemPageCall) DoAndReturn(f func(context.Context, *configuration_center.GetDictItemPageReq) (*configuration_center.GetDictItemPageRes, error)) *MockDrivenGetDictItemPageCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetDictItemType mocks base method.
func (m *MockDriven) GetDictItemType(ctx context.Context, queryType string, dictType ...string) (*configuration_center.GetDictItemTypeResp, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, queryType}
	for _, a := range dictType {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetDictItemType", varargs...)
	ret0, _ := ret[0].(*configuration_center.GetDictItemTypeResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDictItemType indicates an expected call of GetDictItemType.
func (mr *MockDrivenMockRecorder) GetDictItemType(ctx, queryType any, dictType ...any) *MockDrivenGetDictItemTypeCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, queryType}, dictType...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDictItemType", reflect.TypeOf((*MockDriven)(nil).GetDictItemType), varargs...)
	return &MockDrivenGetDictItemTypeCall{Call: call}
}

// MockDrivenGetDictItemTypeCall wrap *gomock.Call
type MockDrivenGetDictItemTypeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetDictItemTypeCall) Return(arg0 *configuration_center.GetDictItemTypeResp, arg1 error) *MockDrivenGetDictItemTypeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetDictItemTypeCall) Do(f func(context.Context, string, ...string) (*configuration_center.GetDictItemTypeResp, error)) *MockDrivenGetDictItemTypeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetDictItemTypeCall) DoAndReturn(f func(context.Context, string, ...string) (*configuration_center.GetDictItemTypeResp, error)) *MockDrivenGetDictItemTypeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetGlobalConfig mocks base method.
func (m *MockDriven) GetGlobalConfig(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGlobalConfig", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGlobalConfig indicates an expected call of GetGlobalConfig.
func (mr *MockDrivenMockRecorder) GetGlobalConfig(ctx, key any) *MockDrivenGetGlobalConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGlobalConfig", reflect.TypeOf((*MockDriven)(nil).GetGlobalConfig), ctx, key)
	return &MockDrivenGetGlobalConfigCall{Call: call}
}

// MockDrivenGetGlobalConfigCall wrap *gomock.Call
type MockDrivenGetGlobalConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetGlobalConfigCall) Return(arg0 string, arg1 error) *MockDrivenGetGlobalConfigCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetGlobalConfigCall) Do(f func(context.Context, string) (string, error)) *MockDrivenGetGlobalConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetGlobalConfigCall) DoAndReturn(f func(context.Context, string) (string, error)) *MockDrivenGetGlobalConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetGlobalSwitch mocks base method.
func (m *MockDriven) GetGlobalSwitch(ctx context.Context, key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGlobalSwitch", ctx, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGlobalSwitch indicates an expected call of GetGlobalSwitch.
func (mr *MockDrivenMockRecorder) GetGlobalSwitch(ctx, key any) *MockDrivenGetGlobalSwitchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGlobalSwitch", reflect.TypeOf((*MockDriven)(nil).GetGlobalSwitch), ctx, key)
	return &MockDrivenGetGlobalSwitchCall{Call: call}
}

// MockDrivenGetGlobalSwitchCall wrap *gomock.Call
type MockDrivenGetGlobalSwitchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetGlobalSwitchCall) Return(arg0 bool, arg1 error) *MockDrivenGetGlobalSwitchCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetGlobalSwitchCall) Do(f func(context.Context, string) (bool, error)) *MockDrivenGetGlobalSwitchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetGlobalSwitchCall) DoAndReturn(f func(context.Context, string) (bool, error)) *MockDrivenGetGlobalSwitchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetGradeLabel mocks base method.
func (m *MockDriven) GetGradeLabel(ctx context.Context, req *configuration_center.GetGradeLabelReq) (*configuration_center.GetGradeLabelRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGradeLabel", ctx, req)
	ret0, _ := ret[0].(*configuration_center.GetGradeLabelRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGradeLabel indicates an expected call of GetGradeLabel.
func (mr *MockDrivenMockRecorder) GetGradeLabel(ctx, req any) *MockDrivenGetGradeLabelCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGradeLabel", reflect.TypeOf((*MockDriven)(nil).GetGradeLabel), ctx, req)
	return &MockDrivenGetGradeLabelCall{Call: call}
}

// MockDrivenGetGradeLabelCall wrap *gomock.Call
type MockDrivenGetGradeLabelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetGradeLabelCall) Return(arg0 *configuration_center.GetGradeLabelRes, arg1 error) *MockDrivenGetGradeLabelCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetGradeLabelCall) Do(f func(context.Context, *configuration_center.GetGradeLabelReq) (*configuration_center.GetGradeLabelRes, error)) *MockDrivenGetGradeLabelCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetGradeLabelCall) DoAndReturn(f func(context.Context, *configuration_center.GetGradeLabelReq) (*configuration_center.GetGradeLabelRes, error)) *MockDrivenGetGradeLabelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetInfoSystemsPrecision mocks base method.
func (m *MockDriven) GetInfoSystemsPrecision(ctx context.Context, ids, names []string) ([]*configuration_center.GetInfoSystemByIdsRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInfoSystemsPrecision", ctx, ids, names)
	ret0, _ := ret[0].([]*configuration_center.GetInfoSystemByIdsRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInfoSystemsPrecision indicates an expected call of GetInfoSystemsPrecision.
func (mr *MockDrivenMockRecorder) GetInfoSystemsPrecision(ctx, ids, names any) *MockDrivenGetInfoSystemsPrecisionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInfoSystemsPrecision", reflect.TypeOf((*MockDriven)(nil).GetInfoSystemsPrecision), ctx, ids, names)
	return &MockDrivenGetInfoSystemsPrecisionCall{Call: call}
}

// MockDrivenGetInfoSystemsPrecisionCall wrap *gomock.Call
type MockDrivenGetInfoSystemsPrecisionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetInfoSystemsPrecisionCall) Return(arg0 []*configuration_center.GetInfoSystemByIdsRes, arg1 error) *MockDrivenGetInfoSystemsPrecisionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetInfoSystemsPrecisionCall) Do(f func(context.Context, []string, []string) ([]*configuration_center.GetInfoSystemByIdsRes, error)) *MockDrivenGetInfoSystemsPrecisionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetInfoSystemsPrecisionCall) DoAndReturn(f func(context.Context, []string, []string) ([]*configuration_center.GetInfoSystemByIdsRes, error)) *MockDrivenGetInfoSystemsPrecisionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetLabelById mocks base method.
func (m *MockDriven) GetLabelById(ctx context.Context, id string) (*configuration_center.GetLabelByIdRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLabelById", ctx, id)
	ret0, _ := ret[0].(*configuration_center.GetLabelByIdRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLabelById indicates an expected call of GetLabelById.
func (mr *MockDrivenMockRecorder) GetLabelById(ctx, id any) *MockDrivenGetLabelByIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLabelById", reflect.TypeOf((*MockDriven)(nil).GetLabelById), ctx, id)
	return &MockDrivenGetLabelByIdCall{Call: call}
}

// MockDrivenGetLabelByIdCall wrap *gomock.Call
type MockDrivenGetLabelByIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetLabelByIdCall) Return(arg0 *configuration_center.GetLabelByIdRes, arg1 error) *MockDrivenGetLabelByIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetLabelByIdCall) Do(f func(context.Context, string) (*configuration_center.GetLabelByIdRes, error)) *MockDrivenGetLabelByIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetLabelByIdCall) DoAndReturn(f func(context.Context, string) (*configuration_center.GetLabelByIdRes, error)) *MockDrivenGetLabelByIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetLabelByIds mocks base method.
func (m *MockDriven) GetLabelByIds(ctx context.Context, ids string) (*configuration_center.GetLabelByIdsRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLabelByIds", ctx, ids)
	ret0, _ := ret[0].(*configuration_center.GetLabelByIdsRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLabelByIds indicates an expected call of GetLabelByIds.
func (mr *MockDrivenMockRecorder) GetLabelByIds(ctx, ids any) *MockDrivenGetLabelByIdsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLabelByIds", reflect.TypeOf((*MockDriven)(nil).GetLabelByIds), ctx, ids)
	return &MockDrivenGetLabelByIdsCall{Call: call}
}

// MockDrivenGetLabelByIdsCall wrap *gomock.Call
type MockDrivenGetLabelByIdsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetLabelByIdsCall) Return(arg0 *configuration_center.GetLabelByIdsRes, arg1 error) *MockDrivenGetLabelByIdsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetLabelByIdsCall) Do(f func(context.Context, string) (*configuration_center.GetLabelByIdsRes, error)) *MockDrivenGetLabelByIdsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetLabelByIdsCall) DoAndReturn(f func(context.Context, string) (*configuration_center.GetLabelByIdsRes, error)) *MockDrivenGetLabelByIdsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetLabelByName mocks base method.
func (m *MockDriven) GetLabelByName(ctx context.Context, name string) (*configuration_center.GetLabelByIdRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLabelByName", ctx, name)
	ret0, _ := ret[0].(*configuration_center.GetLabelByIdRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLabelByName indicates an expected call of GetLabelByName.
func (mr *MockDrivenMockRecorder) GetLabelByName(ctx, name any) *MockDrivenGetLabelByNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLabelByName", reflect.TypeOf((*MockDriven)(nil).GetLabelByName), ctx, name)
	return &MockDrivenGetLabelByNameCall{Call: call}
}

// MockDrivenGetLabelByNameCall wrap *gomock.Call
type MockDrivenGetLabelByNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetLabelByNameCall) Return(arg0 *configuration_center.GetLabelByIdRes, arg1 error) *MockDrivenGetLabelByNameCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetLabelByNameCall) Do(f func(context.Context, string) (*configuration_center.GetLabelByIdRes, error)) *MockDrivenGetLabelByNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetLabelByNameCall) DoAndReturn(f func(context.Context, string) (*configuration_center.GetLabelByIdRes, error)) *MockDrivenGetLabelByNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetProcessBindByAuditType mocks base method.
func (m *MockDriven) GetProcessBindByAuditType(ctx context.Context, auditType *configuration_center.GetProcessBindByAuditTypeReq) (*configuration_center.GetProcessBindByAuditTypeRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProcessBindByAuditType", ctx, auditType)
	ret0, _ := ret[0].(*configuration_center.GetProcessBindByAuditTypeRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProcessBindByAuditType indicates an expected call of GetProcessBindByAuditType.
func (mr *MockDrivenMockRecorder) GetProcessBindByAuditType(ctx, auditType any) *MockDrivenGetProcessBindByAuditTypeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProcessBindByAuditType", reflect.TypeOf((*MockDriven)(nil).GetProcessBindByAuditType), ctx, auditType)
	return &MockDrivenGetProcessBindByAuditTypeCall{Call: call}
}

// MockDrivenGetProcessBindByAuditTypeCall wrap *gomock.Call
type MockDrivenGetProcessBindByAuditTypeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetProcessBindByAuditTypeCall) Return(res *configuration_center.GetProcessBindByAuditTypeRes, err error) *MockDrivenGetProcessBindByAuditTypeCall {
	c.Call = c.Call.Return(res, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetProcessBindByAuditTypeCall) Do(f func(context.Context, *configuration_center.GetProcessBindByAuditTypeReq) (*configuration_center.GetProcessBindByAuditTypeRes, error)) *MockDrivenGetProcessBindByAuditTypeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetProcessBindByAuditTypeCall) DoAndReturn(f func(context.Context, *configuration_center.GetProcessBindByAuditTypeReq) (*configuration_center.GetProcessBindByAuditTypeRes, error)) *MockDrivenGetProcessBindByAuditTypeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetRoleIDs mocks base method.
func (m *MockDriven) GetRoleIDs(ctx context.Context, userID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleIDs", ctx, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleIDs indicates an expected call of GetRoleIDs.
func (mr *MockDrivenMockRecorder) GetRoleIDs(ctx, userID any) *MockDrivenGetRoleIDsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleIDs", reflect.TypeOf((*MockDriven)(nil).GetRoleIDs), ctx, userID)
	return &MockDrivenGetRoleIDsCall{Call: call}
}

// MockDrivenGetRoleIDsCall wrap *gomock.Call
type MockDrivenGetRoleIDsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetRoleIDsCall) Return(arg0 []string, arg1 error) *MockDrivenGetRoleIDsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetRoleIDsCall) Do(f func(context.Context, string) ([]string, error)) *MockDrivenGetRoleIDsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetRoleIDsCall) DoAndReturn(f func(context.Context, string) ([]string, error)) *MockDrivenGetRoleIDsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetRolesInfo mocks base method.
func (m *MockDriven) GetRolesInfo(ctx context.Context, rid, uid string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRolesInfo", ctx, rid, uid)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRolesInfo indicates an expected call of GetRolesInfo.
func (mr *MockDrivenMockRecorder) GetRolesInfo(ctx, rid, uid any) *MockDrivenGetRolesInfoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRolesInfo", reflect.TypeOf((*MockDriven)(nil).GetRolesInfo), ctx, rid, uid)
	return &MockDrivenGetRolesInfoCall{Call: call}
}

// MockDrivenGetRolesInfoCall wrap *gomock.Call
type MockDrivenGetRolesInfoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetRolesInfoCall) Return(arg0 bool, arg1 error) *MockDrivenGetRolesInfoCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetRolesInfoCall) Do(f func(context.Context, string, string) (bool, error)) *MockDrivenGetRolesInfoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetRolesInfoCall) DoAndReturn(f func(context.Context, string, string) (bool, error)) *MockDrivenGetRolesInfoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetThirdPartyAddr mocks base method.
func (m *MockDriven) GetThirdPartyAddr(ctx context.Context, name string) ([]*configuration_center.GetThirdPartyAddressRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThirdPartyAddr", ctx, name)
	ret0, _ := ret[0].([]*configuration_center.GetThirdPartyAddressRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThirdPartyAddr indicates an expected call of GetThirdPartyAddr.
func (mr *MockDrivenMockRecorder) GetThirdPartyAddr(ctx, name any) *MockDrivenGetThirdPartyAddrCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThirdPartyAddr", reflect.TypeOf((*MockDriven)(nil).GetThirdPartyAddr), ctx, name)
	return &MockDrivenGetThirdPartyAddrCall{Call: call}
}

// MockDrivenGetThirdPartyAddrCall wrap *gomock.Call
type MockDrivenGetThirdPartyAddrCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetThirdPartyAddrCall) Return(arg0 []*configuration_center.GetThirdPartyAddressRes, arg1 error) *MockDrivenGetThirdPartyAddrCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetThirdPartyAddrCall) Do(f func(context.Context, string) ([]*configuration_center.GetThirdPartyAddressRes, error)) *MockDrivenGetThirdPartyAddrCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetThirdPartyAddrCall) DoAndReturn(f func(context.Context, string) ([]*configuration_center.GetThirdPartyAddressRes, error)) *MockDrivenGetThirdPartyAddrCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetUser mocks base method.
func (m *MockDriven) GetUser(ctx context.Context, id string, opts configuration_center.GetUserOptions) (*configuration_center.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, id, opts)
	ret0, _ := ret[0].(*configuration_center.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockDrivenMockRecorder) GetUser(ctx, id, opts any) *MockDrivenGetUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockDriven)(nil).GetUser), ctx, id, opts)
	return &MockDrivenGetUserCall{Call: call}
}

// MockDrivenGetUserCall wrap *gomock.Call
type MockDrivenGetUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetUserCall) Return(arg0 *configuration_center.User, arg1 error) *MockDrivenGetUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetUserCall) Do(f func(context.Context, string, configuration_center.GetUserOptions) (*configuration_center.User, error)) *MockDrivenGetUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetUserCall) DoAndReturn(f func(context.Context, string, configuration_center.GetUserOptions) (*configuration_center.User, error)) *MockDrivenGetUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetUserInfo mocks base method.
func (m *MockDriven) GetUserInfo(ctx context.Context, userID string) (*configuration_center.UserRespItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfo", ctx, userID)
	ret0, _ := ret[0].(*configuration_center.UserRespItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfo indicates an expected call of GetUserInfo.
func (mr *MockDrivenMockRecorder) GetUserInfo(ctx, userID any) *MockDrivenGetUserInfoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*MockDriven)(nil).GetUserInfo), ctx, userID)
	return &MockDrivenGetUserInfoCall{Call: call}
}

// MockDrivenGetUserInfoCall wrap *gomock.Call
type MockDrivenGetUserInfoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetUserInfoCall) Return(arg0 *configuration_center.UserRespItem, arg1 error) *MockDrivenGetUserInfoCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetUserInfoCall) Do(f func(context.Context, string) (*configuration_center.UserRespItem, error)) *MockDrivenGetUserInfoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetUserInfoCall) DoAndReturn(f func(context.Context, string) (*configuration_center.UserRespItem, error)) *MockDrivenGetUserInfoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetUserInfoSlice mocks base method.
func (m *MockDriven) GetUserInfoSlice(ctx context.Context, userID ...string) (*base.PageResult[configuration_center.UserRespItem], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range userID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserInfoSlice", varargs...)
	ret0, _ := ret[0].(*base.PageResult[configuration_center.UserRespItem])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfoSlice indicates an expected call of GetUserInfoSlice.
func (mr *MockDrivenMockRecorder) GetUserInfoSlice(ctx any, userID ...any) *MockDrivenGetUserInfoSliceCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, userID...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfoSlice", reflect.TypeOf((*MockDriven)(nil).GetUserInfoSlice), varargs...)
	return &MockDrivenGetUserInfoSliceCall{Call: call}
}

// MockDrivenGetUserInfoSliceCall wrap *gomock.Call
type MockDrivenGetUserInfoSliceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetUserInfoSliceCall) Return(arg0 *base.PageResult[configuration_center.UserRespItem], arg1 error) *MockDrivenGetUserInfoSliceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetUserInfoSliceCall) Do(f func(context.Context, ...string) (*base.PageResult[configuration_center.UserRespItem], error)) *MockDrivenGetUserInfoSliceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetUserInfoSliceCall) DoAndReturn(f func(context.Context, ...string) (*base.PageResult[configuration_center.UserRespItem], error)) *MockDrivenGetUserInfoSliceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetUsers mocks base method.
func (m *MockDriven) GetUsers(ctx context.Context, ids []string) ([]*configuration_center.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers", ctx, ids)
	ret0, _ := ret[0].([]*configuration_center.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockDrivenMockRecorder) GetUsers(ctx, ids any) *MockDrivenGetUsersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockDriven)(nil).GetUsers), ctx, ids)
	return &MockDrivenGetUsersCall{Call: call}
}

// MockDrivenGetUsersCall wrap *gomock.Call
type MockDrivenGetUsersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetUsersCall) Return(arg0 []*configuration_center.User, arg1 error) *MockDrivenGetUsersCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetUsersCall) Do(f func(context.Context, []string) ([]*configuration_center.User, error)) *MockDrivenGetUsersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetUsersCall) DoAndReturn(f func(context.Context, []string) ([]*configuration_center.User, error)) *MockDrivenGetUsersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetUsingType mocks base method.
func (m *MockDriven) GetUsingType(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsingType", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsingType indicates an expected call of GetUsingType.
func (mr *MockDrivenMockRecorder) GetUsingType(ctx any) *MockDrivenGetUsingTypeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsingType", reflect.TypeOf((*MockDriven)(nil).GetUsingType), ctx)
	return &MockDrivenGetUsingTypeCall{Call: call}
}

// MockDrivenGetUsingTypeCall wrap *gomock.Call
type MockDrivenGetUsingTypeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenGetUsingTypeCall) Return(arg0 int, arg1 error) *MockDrivenGetUsingTypeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenGetUsingTypeCall) Do(f func(context.Context) (int, error)) *MockDrivenGetUsingTypeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenGetUsingTypeCall) DoAndReturn(f func(context.Context) (int, error)) *MockDrivenGetUsingTypeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// HasAccessPermission mocks base method.
func (m *MockDriven) HasAccessPermission(ctx context.Context, uid string, accessType access_control.AccessType, resource access_control.Resource) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasAccessPermission", ctx, uid, accessType, resource)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasAccessPermission indicates an expected call of HasAccessPermission.
func (mr *MockDrivenMockRecorder) HasAccessPermission(ctx, uid, accessType, resource any) *MockDrivenHasAccessPermissionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasAccessPermission", reflect.TypeOf((*MockDriven)(nil).HasAccessPermission), ctx, uid, accessType, resource)
	return &MockDrivenHasAccessPermissionCall{Call: call}
}

// MockDrivenHasAccessPermissionCall wrap *gomock.Call
type MockDrivenHasAccessPermissionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenHasAccessPermissionCall) Return(arg0 bool, arg1 error) *MockDrivenHasAccessPermissionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenHasAccessPermissionCall) Do(f func(context.Context, string, access_control.AccessType, access_control.Resource) (bool, error)) *MockDrivenHasAccessPermissionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenHasAccessPermissionCall) DoAndReturn(f func(context.Context, string, access_control.AccessType, access_control.Resource) (bool, error)) *MockDrivenHasAccessPermissionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// HasAccessPermissionApps mocks base method.
func (m *MockDriven) HasAccessPermissionApps(ctx context.Context) (*configuration_center.AppList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasAccessPermissionApps", ctx)
	ret0, _ := ret[0].(*configuration_center.AppList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasAccessPermissionApps indicates an expected call of HasAccessPermissionApps.
func (mr *MockDrivenMockRecorder) HasAccessPermissionApps(ctx any) *MockDrivenHasAccessPermissionAppsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasAccessPermissionApps", reflect.TypeOf((*MockDriven)(nil).HasAccessPermissionApps), ctx)
	return &MockDrivenHasAccessPermissionAppsCall{Call: call}
}

// MockDrivenHasAccessPermissionAppsCall wrap *gomock.Call
type MockDrivenHasAccessPermissionAppsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenHasAccessPermissionAppsCall) Return(arg0 *configuration_center.AppList, arg1 error) *MockDrivenHasAccessPermissionAppsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenHasAccessPermissionAppsCall) Do(f func(context.Context) (*configuration_center.AppList, error)) *MockDrivenHasAccessPermissionAppsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenHasAccessPermissionAppsCall) DoAndReturn(f func(context.Context) (*configuration_center.AppList, error)) *MockDrivenHasAccessPermissionAppsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// HasAppsAccessPermission mocks base method.
func (m *MockDriven) HasAppsAccessPermission(ctx context.Context, uid, resource string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasAppsAccessPermission", ctx, uid, resource)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasAppsAccessPermission indicates an expected call of HasAppsAccessPermission.
func (mr *MockDrivenMockRecorder) HasAppsAccessPermission(ctx, uid, resource any) *MockDrivenHasAppsAccessPermissionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasAppsAccessPermission", reflect.TypeOf((*MockDriven)(nil).HasAppsAccessPermission), ctx, uid, resource)
	return &MockDrivenHasAppsAccessPermissionCall{Call: call}
}

// MockDrivenHasAppsAccessPermissionCall wrap *gomock.Call
type MockDrivenHasAppsAccessPermissionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenHasAppsAccessPermissionCall) Return(arg0 bool, arg1 error) *MockDrivenHasAppsAccessPermissionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenHasAppsAccessPermissionCall) Do(f func(context.Context, string, string) (bool, error)) *MockDrivenHasAppsAccessPermissionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenHasAppsAccessPermissionCall) DoAndReturn(f func(context.Context, string, string) (bool, error)) *MockDrivenHasAppsAccessPermissionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// HasRoles mocks base method.
func (m *MockDriven) HasRoles(ctx context.Context, roles ...string) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range roles {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HasRoles", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasRoles indicates an expected call of HasRoles.
func (mr *MockDrivenMockRecorder) HasRoles(ctx any, roles ...any) *MockDrivenHasRolesCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, roles...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasRoles", reflect.TypeOf((*MockDriven)(nil).HasRoles), varargs...)
	return &MockDrivenHasRolesCall{Call: call}
}

// MockDrivenHasRolesCall wrap *gomock.Call
type MockDrivenHasRolesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenHasRolesCall) Return(arg0 bool, arg1 error) *MockDrivenHasRolesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenHasRolesCall) Do(f func(context.Context, ...string) (bool, error)) *MockDrivenHasRolesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenHasRolesCall) DoAndReturn(f func(context.Context, ...string) (bool, error)) *MockDrivenHasRolesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListApplicationsByDeveloperID mocks base method.
func (m *MockDriven) ListApplicationsByDeveloperID(ctx context.Context, id string) ([]configuration_center.Application, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListApplicationsByDeveloperID", ctx, id)
	ret0, _ := ret[0].([]configuration_center.Application)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListApplicationsByDeveloperID indicates an expected call of ListApplicationsByDeveloperID.
func (mr *MockDrivenMockRecorder) ListApplicationsByDeveloperID(ctx, id any) *MockDrivenListApplicationsByDeveloperIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListApplicationsByDeveloperID", reflect.TypeOf((*MockDriven)(nil).ListApplicationsByDeveloperID), ctx, id)
	return &MockDrivenListApplicationsByDeveloperIDCall{Call: call}
}

// MockDrivenListApplicationsByDeveloperIDCall wrap *gomock.Call
type MockDrivenListApplicationsByDeveloperIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenListApplicationsByDeveloperIDCall) Return(arg0 []configuration_center.Application, arg1 error) *MockDrivenListApplicationsByDeveloperIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenListApplicationsByDeveloperIDCall) Do(f func(context.Context, string) ([]configuration_center.Application, error)) *MockDrivenListApplicationsByDeveloperIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenListApplicationsByDeveloperIDCall) DoAndReturn(f func(context.Context, string) ([]configuration_center.Application, error)) *MockDrivenListApplicationsByDeveloperIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PutGlobalConfig mocks base method.
func (m *MockDriven) PutGlobalConfig(ctx context.Context, key, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutGlobalConfig", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutGlobalConfig indicates an expected call of PutGlobalConfig.
func (mr *MockDrivenMockRecorder) PutGlobalConfig(ctx, key, value any) *MockDrivenPutGlobalConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutGlobalConfig", reflect.TypeOf((*MockDriven)(nil).PutGlobalConfig), ctx, key, value)
	return &MockDrivenPutGlobalConfigCall{Call: call}
}

// MockDrivenPutGlobalConfigCall wrap *gomock.Call
type MockDrivenPutGlobalConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenPutGlobalConfigCall) Return(arg0 error) *MockDrivenPutGlobalConfigCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenPutGlobalConfigCall) Do(f func(context.Context, string, string) error) *MockDrivenPutGlobalConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenPutGlobalConfigCall) DoAndReturn(f func(context.Context, string, string) error) *MockDrivenPutGlobalConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// QueryDataGrade mocks base method.
func (m *MockDriven) QueryDataGrade(ctx context.Context, id ...string) (map[string]*configuration_center.HierarchyTag, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range id {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryDataGrade", varargs...)
	ret0, _ := ret[0].(map[string]*configuration_center.HierarchyTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryDataGrade indicates an expected call of QueryDataGrade.
func (mr *MockDrivenMockRecorder) QueryDataGrade(ctx any, id ...any) *MockDrivenQueryDataGradeCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, id...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryDataGrade", reflect.TypeOf((*MockDriven)(nil).QueryDataGrade), varargs...)
	return &MockDrivenQueryDataGradeCall{Call: call}
}

// MockDrivenQueryDataGradeCall wrap *gomock.Call
type MockDrivenQueryDataGradeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenQueryDataGradeCall) Return(arg0 map[string]*configuration_center.HierarchyTag, arg1 error) *MockDrivenQueryDataGradeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenQueryDataGradeCall) Do(f func(context.Context, ...string) (map[string]*configuration_center.HierarchyTag, error)) *MockDrivenQueryDataGradeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenQueryDataGradeCall) DoAndReturn(f func(context.Context, ...string) (map[string]*configuration_center.HierarchyTag, error)) *MockDrivenQueryDataGradeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UsersRoles mocks base method.
func (m *MockDriven) UsersRoles(ctx context.Context) ([]configuration_center.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UsersRoles", ctx)
	ret0, _ := ret[0].([]configuration_center.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UsersRoles indicates an expected call of UsersRoles.
func (mr *MockDrivenMockRecorder) UsersRoles(ctx any) *MockDrivenUsersRolesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UsersRoles", reflect.TypeOf((*MockDriven)(nil).UsersRoles), ctx)
	return &MockDrivenUsersRolesCall{Call: call}
}

// MockDrivenUsersRolesCall wrap *gomock.Call
type MockDrivenUsersRolesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDrivenUsersRolesCall) Return(arg0 []configuration_center.Role, arg1 error) *MockDrivenUsersRolesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDrivenUsersRolesCall) Do(f func(context.Context) ([]configuration_center.Role, error)) *MockDrivenUsersRolesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDrivenUsersRolesCall) DoAndReturn(f func(context.Context) ([]configuration_center.Role, error)) *MockDrivenUsersRolesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
