// Code generated by MockGen. DO NOT EDIT.
// Source: work_order_task.go
//
// Generated by this command:
//
//	mockgen -destination=mock/work_order_task.go -package=mock -typed -write_generate_directive -source work_order_task.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	v1 "github.com/kweaver-ai/idrm-go-common/api/task_center/v1"
	task_center "github.com/kweaver-ai/idrm-go-common/rest/task_center"
	gomock "go.uber.org/mock/gomock"
)

//go:generate mockgen -destination=mock/work_order_task.go -package=mock -typed -write_generate_directive -source work_order_task.go

// MockWorkOrderTaskGetter is a mock of WorkOrderTaskGetter interface.
type MockWorkOrderTaskGetter struct {
	ctrl     *gomock.Controller
	recorder *MockWorkOrderTaskGetterMockRecorder
	isgomock struct{}
}

// MockWorkOrderTaskGetterMockRecorder is the mock recorder for MockWorkOrderTaskGetter.
type MockWorkOrderTaskGetterMockRecorder struct {
	mock *MockWorkOrderTaskGetter
}

// NewMockWorkOrderTaskGetter creates a new mock instance.
func NewMockWorkOrderTaskGetter(ctrl *gomock.Controller) *MockWorkOrderTaskGetter {
	mock := &MockWorkOrderTaskGetter{ctrl: ctrl}
	mock.recorder = &MockWorkOrderTaskGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkOrderTaskGetter) EXPECT() *MockWorkOrderTaskGetterMockRecorder {
	return m.recorder
}

// WorkOrderTasks mocks base method.
func (m *MockWorkOrderTaskGetter) WorkOrderTasks() task_center.WorkOrderTaskInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkOrderTasks")
	ret0, _ := ret[0].(task_center.WorkOrderTaskInterface)
	return ret0
}

// WorkOrderTasks indicates an expected call of WorkOrderTasks.
func (mr *MockWorkOrderTaskGetterMockRecorder) WorkOrderTasks() *MockWorkOrderTaskGetterWorkOrderTasksCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkOrderTasks", reflect.TypeOf((*MockWorkOrderTaskGetter)(nil).WorkOrderTasks))
	return &MockWorkOrderTaskGetterWorkOrderTasksCall{Call: call}
}

// MockWorkOrderTaskGetterWorkOrderTasksCall wrap *gomock.Call
type MockWorkOrderTaskGetterWorkOrderTasksCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWorkOrderTaskGetterWorkOrderTasksCall) Return(arg0 task_center.WorkOrderTaskInterface) *MockWorkOrderTaskGetterWorkOrderTasksCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWorkOrderTaskGetterWorkOrderTasksCall) Do(f func() task_center.WorkOrderTaskInterface) *MockWorkOrderTaskGetterWorkOrderTasksCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWorkOrderTaskGetterWorkOrderTasksCall) DoAndReturn(f func() task_center.WorkOrderTaskInterface) *MockWorkOrderTaskGetterWorkOrderTasksCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockWorkOrderTaskInterface is a mock of WorkOrderTaskInterface interface.
type MockWorkOrderTaskInterface struct {
	ctrl     *gomock.Controller
	recorder *MockWorkOrderTaskInterfaceMockRecorder
	isgomock struct{}
}

// MockWorkOrderTaskInterfaceMockRecorder is the mock recorder for MockWorkOrderTaskInterface.
type MockWorkOrderTaskInterfaceMockRecorder struct {
	mock *MockWorkOrderTaskInterface
}

// NewMockWorkOrderTaskInterface creates a new mock instance.
func NewMockWorkOrderTaskInterface(ctrl *gomock.Controller) *MockWorkOrderTaskInterface {
	mock := &MockWorkOrderTaskInterface{ctrl: ctrl}
	mock.recorder = &MockWorkOrderTaskInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkOrderTaskInterface) EXPECT() *MockWorkOrderTaskInterfaceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockWorkOrderTaskInterface) Get(ctx context.Context, id string) (*v1.WorkOrderTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*v1.WorkOrderTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockWorkOrderTaskInterfaceMockRecorder) Get(ctx, id any) *MockWorkOrderTaskInterfaceGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockWorkOrderTaskInterface)(nil).Get), ctx, id)
	return &MockWorkOrderTaskInterfaceGetCall{Call: call}
}

// MockWorkOrderTaskInterfaceGetCall wrap *gomock.Call
type MockWorkOrderTaskInterfaceGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWorkOrderTaskInterfaceGetCall) Return(result *v1.WorkOrderTask, err error) *MockWorkOrderTaskInterfaceGetCall {
	c.Call = c.Call.Return(result, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWorkOrderTaskInterfaceGetCall) Do(f func(context.Context, string) (*v1.WorkOrderTask, error)) *MockWorkOrderTaskInterfaceGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWorkOrderTaskInterfaceGetCall) DoAndReturn(f func(context.Context, string) (*v1.WorkOrderTask, error)) *MockWorkOrderTaskInterfaceGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
