// Code generated by MockGen. DO NOT EDIT.
// Source: info_system.go
//
// Generated by this command:
//
//	mockgen -destination=mock/info_system.go -package=mock -typed -write_generate_directive -source info_system.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	v1 "github.com/kweaver-ai/idrm-go-common/api/basic_search/v1"
	v10 "github.com/kweaver-ai/idrm-go-common/rest/basic_search/v1"
	gomock "go.uber.org/mock/gomock"
)

//go:generate mockgen -destination=mock/info_system.go -package=mock -typed -write_generate_directive -source info_system.go

// MockInfoSystemsGetter is a mock of InfoSystemsGetter interface.
type MockInfoSystemsGetter struct {
	ctrl     *gomock.Controller
	recorder *MockInfoSystemsGetterMockRecorder
	isgomock struct{}
}

// MockInfoSystemsGetterMockRecorder is the mock recorder for MockInfoSystemsGetter.
type MockInfoSystemsGetterMockRecorder struct {
	mock *MockInfoSystemsGetter
}

// NewMockInfoSystemsGetter creates a new mock instance.
func NewMockInfoSystemsGetter(ctrl *gomock.Controller) *MockInfoSystemsGetter {
	mock := &MockInfoSystemsGetter{ctrl: ctrl}
	mock.recorder = &MockInfoSystemsGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInfoSystemsGetter) EXPECT() *MockInfoSystemsGetterMockRecorder {
	return m.recorder
}

// InfoSystems mocks base method.
func (m *MockInfoSystemsGetter) InfoSystems() v10.InfoSystemInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InfoSystems")
	ret0, _ := ret[0].(v10.InfoSystemInterface)
	return ret0
}

// InfoSystems indicates an expected call of InfoSystems.
func (mr *MockInfoSystemsGetterMockRecorder) InfoSystems() *MockInfoSystemsGetterInfoSystemsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InfoSystems", reflect.TypeOf((*MockInfoSystemsGetter)(nil).InfoSystems))
	return &MockInfoSystemsGetterInfoSystemsCall{Call: call}
}

// MockInfoSystemsGetterInfoSystemsCall wrap *gomock.Call
type MockInfoSystemsGetterInfoSystemsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockInfoSystemsGetterInfoSystemsCall) Return(arg0 v10.InfoSystemInterface) *MockInfoSystemsGetterInfoSystemsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockInfoSystemsGetterInfoSystemsCall) Do(f func() v10.InfoSystemInterface) *MockInfoSystemsGetterInfoSystemsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockInfoSystemsGetterInfoSystemsCall) DoAndReturn(f func() v10.InfoSystemInterface) *MockInfoSystemsGetterInfoSystemsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockInfoSystemInterface is a mock of InfoSystemInterface interface.
type MockInfoSystemInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInfoSystemInterfaceMockRecorder
	isgomock struct{}
}

// MockInfoSystemInterfaceMockRecorder is the mock recorder for MockInfoSystemInterface.
type MockInfoSystemInterfaceMockRecorder struct {
	mock *MockInfoSystemInterface
}

// NewMockInfoSystemInterface creates a new mock instance.
func NewMockInfoSystemInterface(ctrl *gomock.Controller) *MockInfoSystemInterface {
	mock := &MockInfoSystemInterface{ctrl: ctrl}
	mock.recorder = &MockInfoSystemInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInfoSystemInterface) EXPECT() *MockInfoSystemInterfaceMockRecorder {
	return m.recorder
}

// Search mocks base method.
func (m *MockInfoSystemInterface) Search(ctx context.Context, query *v1.InfoSystemSearchQuery, opts *v1.InfoSystemSearchOptions) (*v1.InfoSystemSearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, query, opts)
	ret0, _ := ret[0].(*v1.InfoSystemSearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockInfoSystemInterfaceMockRecorder) Search(ctx, query, opts any) *MockInfoSystemInterfaceSearchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockInfoSystemInterface)(nil).Search), ctx, query, opts)
	return &MockInfoSystemInterfaceSearchCall{Call: call}
}

// MockInfoSystemInterfaceSearchCall wrap *gomock.Call
type MockInfoSystemInterfaceSearchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockInfoSystemInterfaceSearchCall) Return(arg0 *v1.InfoSystemSearchResult, arg1 error) *MockInfoSystemInterfaceSearchCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockInfoSystemInterfaceSearchCall) Do(f func(context.Context, *v1.InfoSystemSearchQuery, *v1.InfoSystemSearchOptions) (*v1.InfoSystemSearchResult, error)) *MockInfoSystemInterfaceSearchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockInfoSystemInterfaceSearchCall) DoAndReturn(f func(context.Context, *v1.InfoSystemSearchQuery, *v1.InfoSystemSearchOptions) (*v1.InfoSystemSearchResult, error)) *MockInfoSystemInterfaceSearchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
