// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kweaver-ai/idrm-go-common/rest/hydra (interfaces: Hydra)
//
// Generated by this command:
//
//	mockgen -destination=hydra.go -package=mock -typed -write_generate_directive github.com/kweaver-ai/idrm-go-common/rest/hydra Hydra
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	hydra "github.com/kweaver-ai/idrm-go-common/rest/hydra"
	gomock "go.uber.org/mock/gomock"
)

//go:generate mockgen -destination=hydra.go -package=mock -typed -write_generate_directive github.com/kweaver-ai/idrm-go-common/rest/hydra Hydra

// MockHydra is a mock of Hydra interface.
type MockHydra struct {
	ctrl     *gomock.Controller
	recorder *MockHydraMockRecorder
}

// MockHydraMockRecorder is the mock recorder for MockHydra.
type MockHydraMockRecorder struct {
	mock *MockHydra
}

// NewMockHydra creates a new mock instance.
func NewMockHydra(ctrl *gomock.Controller) *MockHydra {
	mock := &MockHydra{ctrl: ctrl}
	mock.recorder = &MockHydraMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHydra) EXPECT() *MockHydraMockRecorder {
	return m.recorder
}

// GetClientCredentialToken mocks base method.
func (m *MockHydra) GetClientCredentialToken(arg0 context.Context, arg1, arg2 string) (string, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientCredentialToken", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetClientCredentialToken indicates an expected call of GetClientCredentialToken.
func (mr *MockHydraMockRecorder) GetClientCredentialToken(arg0, arg1, arg2 any) *MockHydraGetClientCredentialTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientCredentialToken", reflect.TypeOf((*MockHydra)(nil).GetClientCredentialToken), arg0, arg1, arg2)
	return &MockHydraGetClientCredentialTokenCall{Call: call}
}

// MockHydraGetClientCredentialTokenCall wrap *gomock.Call
type MockHydraGetClientCredentialTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHydraGetClientCredentialTokenCall) Return(arg0 string, arg1 int64, arg2 error) *MockHydraGetClientCredentialTokenCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHydraGetClientCredentialTokenCall) Do(f func(context.Context, string, string) (string, int64, error)) *MockHydraGetClientCredentialTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHydraGetClientCredentialTokenCall) DoAndReturn(f func(context.Context, string, string) (string, int64, error)) *MockHydraGetClientCredentialTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetClientNameById mocks base method.
func (m *MockHydra) GetClientNameById(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientNameById", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientNameById indicates an expected call of GetClientNameById.
func (mr *MockHydraMockRecorder) GetClientNameById(arg0, arg1 any) *MockHydraGetClientNameByIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientNameById", reflect.TypeOf((*MockHydra)(nil).GetClientNameById), arg0, arg1)
	return &MockHydraGetClientNameByIdCall{Call: call}
}

// MockHydraGetClientNameByIdCall wrap *gomock.Call
type MockHydraGetClientNameByIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHydraGetClientNameByIdCall) Return(arg0 string, arg1 error) *MockHydraGetClientNameByIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHydraGetClientNameByIdCall) Do(f func(context.Context, string) (string, error)) *MockHydraGetClientNameByIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHydraGetClientNameByIdCall) DoAndReturn(f func(context.Context, string) (string, error)) *MockHydraGetClientNameByIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Introspect mocks base method.
func (m *MockHydra) Introspect(arg0 context.Context, arg1 string) (hydra.TokenIntrospectInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Introspect", arg0, arg1)
	ret0, _ := ret[0].(hydra.TokenIntrospectInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Introspect indicates an expected call of Introspect.
func (mr *MockHydraMockRecorder) Introspect(arg0, arg1 any) *MockHydraIntrospectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Introspect", reflect.TypeOf((*MockHydra)(nil).Introspect), arg0, arg1)
	return &MockHydraIntrospectCall{Call: call}
}

// MockHydraIntrospectCall wrap *gomock.Call
type MockHydraIntrospectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHydraIntrospectCall) Return(arg0 hydra.TokenIntrospectInfo, arg1 error) *MockHydraIntrospectCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHydraIntrospectCall) Do(f func(context.Context, string) (hydra.TokenIntrospectInfo, error)) *MockHydraIntrospectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHydraIntrospectCall) DoAndReturn(f func(context.Context, string) (hydra.TokenIntrospectInfo, error)) *MockHydraIntrospectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RegistCredentialClient mocks base method.
func (m *MockHydra) RegistCredentialClient(arg0 context.Context, arg1, arg2 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegistCredentialClient", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegistCredentialClient indicates an expected call of RegistCredentialClient.
func (mr *MockHydraMockRecorder) RegistCredentialClient(arg0, arg1, arg2 any) *MockHydraRegistCredentialClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegistCredentialClient", reflect.TypeOf((*MockHydra)(nil).RegistCredentialClient), arg0, arg1, arg2)
	return &MockHydraRegistCredentialClientCall{Call: call}
}

// MockHydraRegistCredentialClientCall wrap *gomock.Call
type MockHydraRegistCredentialClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHydraRegistCredentialClientCall) Return(arg0 string, arg1 error) *MockHydraRegistCredentialClientCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHydraRegistCredentialClientCall) Do(f func(context.Context, string, string) (string, error)) *MockHydraRegistCredentialClientCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHydraRegistCredentialClientCall) DoAndReturn(f func(context.Context, string, string) (string, error)) *MockHydraRegistCredentialClientCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
