// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: callback/data_catalog/v1/data_push.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 枚举类型定义
type TaskTypeEnum int32

const (
	TaskTypeEnum_task_type_unspecified TaskTypeEnum = 0 // 默认值，必须为0
	TaskTypeEnum_collection            TaskTypeEnum = 1
	TaskTypeEnum_exchange              TaskTypeEnum = 2
	TaskTypeEnum_push                  TaskTypeEnum = 3
)

// Enum value maps for TaskTypeEnum.
var (
	TaskTypeEnum_name = map[int32]string{
		0: "task_type_unspecified",
		1: "collection",
		2: "exchange",
		3: "push",
	}
	TaskTypeEnum_value = map[string]int32{
		"task_type_unspecified": 0,
		"collection":            1,
		"exchange":              2,
		"push":                  3,
	}
)

func (x TaskTypeEnum) Enum() *TaskTypeEnum {
	p := new(TaskTypeEnum)
	*p = x
	return p
}

func (x TaskTypeEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskTypeEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_callback_data_catalog_v1_data_push_proto_enumTypes[0].Descriptor()
}

func (TaskTypeEnum) Type() protoreflect.EnumType {
	return &file_callback_data_catalog_v1_data_push_proto_enumTypes[0]
}

func (x TaskTypeEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskTypeEnum.Descriptor instead.
func (TaskTypeEnum) EnumDescriptor() ([]byte, []int) {
	return file_callback_data_catalog_v1_data_push_proto_rawDescGZIP(), []int{0}
}

type TaskStatusEnum int32

const (
	TaskStatusEnum_unspecified TaskStatusEnum = 0 // 默认值，必须为0
	TaskStatusEnum_waiting     TaskStatusEnum = 1 // 待发布
	TaskStatusEnum_notStarted  TaskStatusEnum = 2 // 未开始
	TaskStatusEnum_inProgress  TaskStatusEnum = 3 // 进行中
	TaskStatusEnum_completed   TaskStatusEnum = 4 // 已结束
	TaskStatusEnum_stopped     TaskStatusEnum = 5 // 已停用
)

// Enum value maps for TaskStatusEnum.
var (
	TaskStatusEnum_name = map[int32]string{
		0: "unspecified",
		1: "waiting",
		2: "notStarted",
		3: "inProgress",
		4: "completed",
		5: "stopped",
	}
	TaskStatusEnum_value = map[string]int32{
		"unspecified": 0,
		"waiting":     1,
		"notStarted":  2,
		"inProgress":  3,
		"completed":   4,
		"stopped":     5,
	}
)

func (x TaskStatusEnum) Enum() *TaskStatusEnum {
	p := new(TaskStatusEnum)
	*p = x
	return p
}

func (x TaskStatusEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatusEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_callback_data_catalog_v1_data_push_proto_enumTypes[1].Descriptor()
}

func (TaskStatusEnum) Type() protoreflect.EnumType {
	return &file_callback_data_catalog_v1_data_push_proto_enumTypes[1]
}

func (x TaskStatusEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatusEnum.Descriptor instead.
func (TaskStatusEnum) EnumDescriptor() ([]byte, []int) {
	return file_callback_data_catalog_v1_data_push_proto_rawDescGZIP(), []int{1}
}

type ExecutionStatusEnum int32

const (
	ExecutionStatusEnum_execution_status_unspecified ExecutionStatusEnum = 0 // 默认值，必须为0
	ExecutionStatusEnum_execution_not_started        ExecutionStatusEnum = 1 // 未开始
	ExecutionStatusEnum_execution_in_progress        ExecutionStatusEnum = 2 // 进行中
	ExecutionStatusEnum_execution_completed          ExecutionStatusEnum = 3 // 已结束
	ExecutionStatusEnum_execution_stopped            ExecutionStatusEnum = 4 // 已停用
	ExecutionStatusEnum_execution_pause              ExecutionStatusEnum = 5 // 暂停
	ExecutionStatusEnum_execution_success            ExecutionStatusEnum = 6 // 成功
	ExecutionStatusEnum_execution_fail               ExecutionStatusEnum = 7 // 失败
)

// Enum value maps for ExecutionStatusEnum.
var (
	ExecutionStatusEnum_name = map[int32]string{
		0: "execution_status_unspecified",
		1: "execution_not_started",
		2: "execution_in_progress",
		3: "execution_completed",
		4: "execution_stopped",
		5: "execution_pause",
		6: "execution_success",
		7: "execution_fail",
	}
	ExecutionStatusEnum_value = map[string]int32{
		"execution_status_unspecified": 0,
		"execution_not_started":        1,
		"execution_in_progress":        2,
		"execution_completed":          3,
		"execution_stopped":            4,
		"execution_pause":              5,
		"execution_success":            6,
		"execution_fail":               7,
	}
)

func (x ExecutionStatusEnum) Enum() *ExecutionStatusEnum {
	p := new(ExecutionStatusEnum)
	*p = x
	return p
}

func (x ExecutionStatusEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionStatusEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_callback_data_catalog_v1_data_push_proto_enumTypes[2].Descriptor()
}

func (ExecutionStatusEnum) Type() protoreflect.EnumType {
	return &file_callback_data_catalog_v1_data_push_proto_enumTypes[2]
}

func (x ExecutionStatusEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionStatusEnum.Descriptor instead.
func (ExecutionStatusEnum) EnumDescriptor() ([]byte, []int) {
	return file_callback_data_catalog_v1_data_push_proto_rawDescGZIP(), []int{2}
}

// 任务信息
type TaskInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TenantId           int64                  `protobuf:"varint,1,opt,name=tenantId,proto3" json:"tenantId,omitempty"`                                                         // 租户Id
	SpaceId            *int64                 `protobuf:"varint,2,opt,name=spaceId,proto3,oneof" json:"spaceId,omitempty"`                                                     // 空间Id
	TaskType           TaskTypeEnum           `protobuf:"varint,3,opt,name=taskType,proto3,enum=data_catalog.v1.TaskTypeEnum" json:"taskType,omitempty"`                       // 任务类型: collection-采集任务; exchange-交换任务; push-推送任务
	TaskName           string                 `protobuf:"bytes,4,opt,name=taskName,proto3" json:"taskName,omitempty"`                                                          // 一个任务存在多个采集/交换动作
	DeptCode           string                 `protobuf:"bytes,5,opt,name=deptCode,proto3" json:"deptCode,omitempty"`                                                          // 所属部门
	TaskStatus         TaskStatusEnum         `protobuf:"varint,6,opt,name=taskStatus,proto3,enum=data_catalog.v1.TaskStatusEnum" json:"taskStatus,omitempty"`                 // notStarted-未开始, inProgress-进行中, completed-已结束, stopped-已停用
	TaskCreateUser     string                 `protobuf:"bytes,7,opt,name=taskCreateUser,proto3" json:"taskCreateUser,omitempty"`                                              // 任务创建人
	TaskCreateTime     string                 `protobuf:"bytes,8,opt,name=taskCreateTime,proto3" json:"taskCreateTime,omitempty"`                                              // 任务创建时间
	ExecutionId        int64                  `protobuf:"varint,9,opt,name=executionId,proto3" json:"executionId,omitempty"`                                                   // 执行任务Id (对应爱数: 作业监控Id)
	ExecutionName      string                 `protobuf:"bytes,10,opt,name=executionName,proto3" json:"executionName,omitempty"`                                               // 执行任务名称，最小单位 (对应爱数: 模型名称+任务id)
	ExecutionStartTime string                 `protobuf:"bytes,11,opt,name=executionStartTime,proto3" json:"executionStartTime,omitempty"`                                     // 执行任务开始时间
	ExecutionEndTime   *string                `protobuf:"bytes,12,opt,name=executionEndTime,proto3,oneof" json:"executionEndTime,omitempty"`                                   // 执行任务完成时间
	ExecutionStatus    ExecutionStatusEnum    `protobuf:"varint,13,opt,name=executionStatus,proto3,enum=data_catalog.v1.ExecutionStatusEnum" json:"executionStatus,omitempty"` // notStarted-未开始, inProgress-进行中, completed-已结束, stopped-已停用, pause-暂停, success-成功, fail-失败
	SourceStatistics   *Statistics            `protobuf:"bytes,14,opt,name=sourceStatistics,proto3" json:"sourceStatistics,omitempty"`                                         // 来源统计数据: 对于爱数对应推送数据来源，对于采集系统对应采集数据来源
	TargetStatistics   *Statistics            `protobuf:"bytes,15,opt,name=targetStatistics,proto3" json:"targetStatistics,omitempty"`                                         // 目标统计数据: 对于爱数对应推送数据目的，对于采集系统对应采集数据目的
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TaskInfo) Reset() {
	*x = TaskInfo{}
	mi := &file_callback_data_catalog_v1_data_push_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfo) ProtoMessage() {}

func (x *TaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_callback_data_catalog_v1_data_push_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfo.ProtoReflect.Descriptor instead.
func (*TaskInfo) Descriptor() ([]byte, []int) {
	return file_callback_data_catalog_v1_data_push_proto_rawDescGZIP(), []int{0}
}

func (x *TaskInfo) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *TaskInfo) GetSpaceId() int64 {
	if x != nil && x.SpaceId != nil {
		return *x.SpaceId
	}
	return 0
}

func (x *TaskInfo) GetTaskType() TaskTypeEnum {
	if x != nil {
		return x.TaskType
	}
	return TaskTypeEnum_task_type_unspecified
}

func (x *TaskInfo) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *TaskInfo) GetDeptCode() string {
	if x != nil {
		return x.DeptCode
	}
	return ""
}

func (x *TaskInfo) GetTaskStatus() TaskStatusEnum {
	if x != nil {
		return x.TaskStatus
	}
	return TaskStatusEnum_unspecified
}

func (x *TaskInfo) GetTaskCreateUser() string {
	if x != nil {
		return x.TaskCreateUser
	}
	return ""
}

func (x *TaskInfo) GetTaskCreateTime() string {
	if x != nil {
		return x.TaskCreateTime
	}
	return ""
}

func (x *TaskInfo) GetExecutionId() int64 {
	if x != nil {
		return x.ExecutionId
	}
	return 0
}

func (x *TaskInfo) GetExecutionName() string {
	if x != nil {
		return x.ExecutionName
	}
	return ""
}

func (x *TaskInfo) GetExecutionStartTime() string {
	if x != nil {
		return x.ExecutionStartTime
	}
	return ""
}

func (x *TaskInfo) GetExecutionEndTime() string {
	if x != nil && x.ExecutionEndTime != nil {
		return *x.ExecutionEndTime
	}
	return ""
}

func (x *TaskInfo) GetExecutionStatus() ExecutionStatusEnum {
	if x != nil {
		return x.ExecutionStatus
	}
	return ExecutionStatusEnum_execution_status_unspecified
}

func (x *TaskInfo) GetSourceStatistics() *Statistics {
	if x != nil {
		return x.SourceStatistics
	}
	return nil
}

func (x *TaskInfo) GetTargetStatistics() *Statistics {
	if x != nil {
		return x.TargetStatistics
	}
	return nil
}

// 统计信息
type Statistics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DatabaseId     int64                  `protobuf:"varint,1,opt,name=databaseId,proto3" json:"databaseId,omitempty"`               // 前置库Id
	DeptCode       *string                `protobuf:"bytes,2,opt,name=deptCode,proto3,oneof" json:"deptCode,omitempty"`              // 所属部门，未填写则使用任务填写部门
	DatasourceId   int64                  `protobuf:"varint,3,opt,name=datasourceId,proto3" json:"datasourceId,omitempty"`           // 数据源Id
	DatasourceName *string                `protobuf:"bytes,4,opt,name=datasourceName,proto3,oneof" json:"datasourceName,omitempty"`  // 数据源名称
	DatasourceIp   *string                `protobuf:"bytes,5,opt,name=datasourceIp,proto3,oneof" json:"datasourceIp,omitempty"`      // 数据源Ip
	DatasourcePort *int32                 `protobuf:"varint,6,opt,name=datasourcePort,proto3,oneof" json:"datasourcePort,omitempty"` // 数据源端口
	DatabaseName   *string                `protobuf:"bytes,7,opt,name=databaseName,proto3,oneof" json:"databaseName,omitempty"`      // 数据库名称
	TableName      string                 `protobuf:"bytes,8,opt,name=tableName,proto3" json:"tableName,omitempty"`                  // 数据表名称
	TotalAmount    int64                  `protobuf:"varint,9,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`             // 数据量
	Type           string                 `protobuf:"bytes,10,opt,name=type,proto3" json:"type,omitempty"`                           // 目前就是全量、增量两种
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Statistics) Reset() {
	*x = Statistics{}
	mi := &file_callback_data_catalog_v1_data_push_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Statistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statistics) ProtoMessage() {}

func (x *Statistics) ProtoReflect() protoreflect.Message {
	mi := &file_callback_data_catalog_v1_data_push_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statistics.ProtoReflect.Descriptor instead.
func (*Statistics) Descriptor() ([]byte, []int) {
	return file_callback_data_catalog_v1_data_push_proto_rawDescGZIP(), []int{1}
}

func (x *Statistics) GetDatabaseId() int64 {
	if x != nil {
		return x.DatabaseId
	}
	return 0
}

func (x *Statistics) GetDeptCode() string {
	if x != nil && x.DeptCode != nil {
		return *x.DeptCode
	}
	return ""
}

func (x *Statistics) GetDatasourceId() int64 {
	if x != nil {
		return x.DatasourceId
	}
	return 0
}

func (x *Statistics) GetDatasourceName() string {
	if x != nil && x.DatasourceName != nil {
		return *x.DatasourceName
	}
	return ""
}

func (x *Statistics) GetDatasourceIp() string {
	if x != nil && x.DatasourceIp != nil {
		return *x.DatasourceIp
	}
	return ""
}

func (x *Statistics) GetDatasourcePort() int32 {
	if x != nil && x.DatasourcePort != nil {
		return *x.DatasourcePort
	}
	return 0
}

func (x *Statistics) GetDatabaseName() string {
	if x != nil && x.DatabaseName != nil {
		return *x.DatabaseName
	}
	return ""
}

func (x *Statistics) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *Statistics) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Statistics) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// 请求和响应消息
type CompleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskInfo            `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTaskRequest) Reset() {
	*x = CompleteTaskRequest{}
	mi := &file_callback_data_catalog_v1_data_push_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTaskRequest) ProtoMessage() {}

func (x *CompleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_callback_data_catalog_v1_data_push_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTaskRequest.ProtoReflect.Descriptor instead.
func (*CompleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_callback_data_catalog_v1_data_push_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteTaskRequest) GetTasks() []*TaskInfo {
	if x != nil {
		return x.Tasks
	}
	return nil
}

var File_callback_data_catalog_v1_data_push_proto protoreflect.FileDescriptor

const file_callback_data_catalog_v1_data_push_proto_rawDesc = "" +
	"\n" +
	"(callback/data_catalog/v1/data_push.proto\x12\x0fdata_catalog.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xf5\x05\n" +
	"\bTaskInfo\x12\x1a\n" +
	"\btenantId\x18\x01 \x01(\x03R\btenantId\x12\x1d\n" +
	"\aspaceId\x18\x02 \x01(\x03H\x00R\aspaceId\x88\x01\x01\x129\n" +
	"\btaskType\x18\x03 \x01(\x0e2\x1d.data_catalog.v1.TaskTypeEnumR\btaskType\x12\x1a\n" +
	"\btaskName\x18\x04 \x01(\tR\btaskName\x12\x1a\n" +
	"\bdeptCode\x18\x05 \x01(\tR\bdeptCode\x12?\n" +
	"\n" +
	"taskStatus\x18\x06 \x01(\x0e2\x1f.data_catalog.v1.TaskStatusEnumR\n" +
	"taskStatus\x12&\n" +
	"\x0etaskCreateUser\x18\a \x01(\tR\x0etaskCreateUser\x12&\n" +
	"\x0etaskCreateTime\x18\b \x01(\tR\x0etaskCreateTime\x12 \n" +
	"\vexecutionId\x18\t \x01(\x03R\vexecutionId\x12$\n" +
	"\rexecutionName\x18\n" +
	" \x01(\tR\rexecutionName\x12.\n" +
	"\x12executionStartTime\x18\v \x01(\tR\x12executionStartTime\x12/\n" +
	"\x10executionEndTime\x18\f \x01(\tH\x01R\x10executionEndTime\x88\x01\x01\x12N\n" +
	"\x0fexecutionStatus\x18\r \x01(\x0e2$.data_catalog.v1.ExecutionStatusEnumR\x0fexecutionStatus\x12G\n" +
	"\x10sourceStatistics\x18\x0e \x01(\v2\x1b.data_catalog.v1.StatisticsR\x10sourceStatistics\x12G\n" +
	"\x10targetStatistics\x18\x0f \x01(\v2\x1b.data_catalog.v1.StatisticsR\x10targetStatisticsB\n" +
	"\n" +
	"\b_spaceIdB\x13\n" +
	"\x11_executionEndTime\"\xc6\x03\n" +
	"\n" +
	"Statistics\x12\x1e\n" +
	"\n" +
	"databaseId\x18\x01 \x01(\x03R\n" +
	"databaseId\x12\x1f\n" +
	"\bdeptCode\x18\x02 \x01(\tH\x00R\bdeptCode\x88\x01\x01\x12\"\n" +
	"\fdatasourceId\x18\x03 \x01(\x03R\fdatasourceId\x12+\n" +
	"\x0edatasourceName\x18\x04 \x01(\tH\x01R\x0edatasourceName\x88\x01\x01\x12'\n" +
	"\fdatasourceIp\x18\x05 \x01(\tH\x02R\fdatasourceIp\x88\x01\x01\x12+\n" +
	"\x0edatasourcePort\x18\x06 \x01(\x05H\x03R\x0edatasourcePort\x88\x01\x01\x12'\n" +
	"\fdatabaseName\x18\a \x01(\tH\x04R\fdatabaseName\x88\x01\x01\x12\x1c\n" +
	"\ttableName\x18\b \x01(\tR\ttableName\x12 \n" +
	"\vtotalAmount\x18\t \x01(\x03R\vtotalAmount\x12\x12\n" +
	"\x04type\x18\n" +
	" \x01(\tR\x04typeB\v\n" +
	"\t_deptCodeB\x11\n" +
	"\x0f_datasourceNameB\x0f\n" +
	"\r_datasourceIpB\x11\n" +
	"\x0f_datasourcePortB\x0f\n" +
	"\r_databaseName\"F\n" +
	"\x13CompleteTaskRequest\x12/\n" +
	"\x05tasks\x18\x01 \x03(\v2\x19.data_catalog.v1.TaskInfoR\x05tasks*Q\n" +
	"\fTaskTypeEnum\x12\x19\n" +
	"\x15task_type_unspecified\x10\x00\x12\x0e\n" +
	"\n" +
	"collection\x10\x01\x12\f\n" +
	"\bexchange\x10\x02\x12\b\n" +
	"\x04push\x10\x03*j\n" +
	"\x0eTaskStatusEnum\x12\x0f\n" +
	"\vunspecified\x10\x00\x12\v\n" +
	"\awaiting\x10\x01\x12\x0e\n" +
	"\n" +
	"notStarted\x10\x02\x12\x0e\n" +
	"\n" +
	"inProgress\x10\x03\x12\r\n" +
	"\tcompleted\x10\x04\x12\v\n" +
	"\astopped\x10\x05*\xdd\x01\n" +
	"\x13ExecutionStatusEnum\x12 \n" +
	"\x1cexecution_status_unspecified\x10\x00\x12\x19\n" +
	"\x15execution_not_started\x10\x01\x12\x19\n" +
	"\x15execution_in_progress\x10\x02\x12\x17\n" +
	"\x13execution_completed\x10\x03\x12\x15\n" +
	"\x11execution_stopped\x10\x04\x12\x13\n" +
	"\x0fexecution_pause\x10\x05\x12\x15\n" +
	"\x11execution_success\x10\x06\x12\x12\n" +
	"\x0eexecution_fail\x10\a2g\n" +
	"\x17DataPushCallbackService\x12L\n" +
	"\fCompleteTask\x12$.data_catalog.v1.CompleteTaskRequest\x1a\x16.google.protobuf.EmptyB:Z8github.com/kweaver-ai/idrm-go-common/api/data_catalog/v1b\x06proto3"

var (
	file_callback_data_catalog_v1_data_push_proto_rawDescOnce sync.Once
	file_callback_data_catalog_v1_data_push_proto_rawDescData []byte
)

func file_callback_data_catalog_v1_data_push_proto_rawDescGZIP() []byte {
	file_callback_data_catalog_v1_data_push_proto_rawDescOnce.Do(func() {
		file_callback_data_catalog_v1_data_push_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_callback_data_catalog_v1_data_push_proto_rawDesc), len(file_callback_data_catalog_v1_data_push_proto_rawDesc)))
	})
	return file_callback_data_catalog_v1_data_push_proto_rawDescData
}

var file_callback_data_catalog_v1_data_push_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_callback_data_catalog_v1_data_push_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_callback_data_catalog_v1_data_push_proto_goTypes = []any{
	(TaskTypeEnum)(0),           // 0: data_catalog.v1.TaskTypeEnum
	(TaskStatusEnum)(0),         // 1: data_catalog.v1.TaskStatusEnum
	(ExecutionStatusEnum)(0),    // 2: data_catalog.v1.ExecutionStatusEnum
	(*TaskInfo)(nil),            // 3: data_catalog.v1.TaskInfo
	(*Statistics)(nil),          // 4: data_catalog.v1.Statistics
	(*CompleteTaskRequest)(nil), // 5: data_catalog.v1.CompleteTaskRequest
	(*emptypb.Empty)(nil),       // 6: google.protobuf.Empty
}
var file_callback_data_catalog_v1_data_push_proto_depIdxs = []int32{
	0, // 0: data_catalog.v1.TaskInfo.taskType:type_name -> data_catalog.v1.TaskTypeEnum
	1, // 1: data_catalog.v1.TaskInfo.taskStatus:type_name -> data_catalog.v1.TaskStatusEnum
	2, // 2: data_catalog.v1.TaskInfo.executionStatus:type_name -> data_catalog.v1.ExecutionStatusEnum
	4, // 3: data_catalog.v1.TaskInfo.sourceStatistics:type_name -> data_catalog.v1.Statistics
	4, // 4: data_catalog.v1.TaskInfo.targetStatistics:type_name -> data_catalog.v1.Statistics
	3, // 5: data_catalog.v1.CompleteTaskRequest.tasks:type_name -> data_catalog.v1.TaskInfo
	5, // 6: data_catalog.v1.DataPushCallbackService.CompleteTask:input_type -> data_catalog.v1.CompleteTaskRequest
	6, // 7: data_catalog.v1.DataPushCallbackService.CompleteTask:output_type -> google.protobuf.Empty
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_callback_data_catalog_v1_data_push_proto_init() }
func file_callback_data_catalog_v1_data_push_proto_init() {
	if File_callback_data_catalog_v1_data_push_proto != nil {
		return
	}
	file_callback_data_catalog_v1_data_push_proto_msgTypes[0].OneofWrappers = []any{}
	file_callback_data_catalog_v1_data_push_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_callback_data_catalog_v1_data_push_proto_rawDesc), len(file_callback_data_catalog_v1_data_push_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_callback_data_catalog_v1_data_push_proto_goTypes,
		DependencyIndexes: file_callback_data_catalog_v1_data_push_proto_depIdxs,
		EnumInfos:         file_callback_data_catalog_v1_data_push_proto_enumTypes,
		MessageInfos:      file_callback_data_catalog_v1_data_push_proto_msgTypes,
	}.Build()
	File_callback_data_catalog_v1_data_push_proto = out.File
	file_callback_data_catalog_v1_data_push_proto_goTypes = nil
	file_callback_data_catalog_v1_data_push_proto_depIdxs = nil
}
