// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: data_push.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataPushCallbackService_CompleteTask_FullMethodName = "/data_catalog.v1.DataPushCallbackService/CompleteTask"
)

// DataPushCallbackServiceClient is the client API for DataPushCallbackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 服务定义
type DataPushCallbackServiceClient interface {
	// 任务相关操作
	CompleteTask(ctx context.Context, in *CompleteTaskRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type dataPushCallbackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataPushCallbackServiceClient(cc grpc.ClientConnInterface) DataPushCallbackServiceClient {
	return &dataPushCallbackServiceClient{cc}
}

func (c *dataPushCallbackServiceClient) CompleteTask(ctx context.Context, in *CompleteTaskRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DataPushCallbackService_CompleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataPushCallbackServiceServer is the server API for DataPushCallbackService service.
// All implementations must embed UnimplementedDataPushCallbackServiceServer
// for forward compatibility.
//
// 服务定义
type DataPushCallbackServiceServer interface {
	// 任务相关操作
	CompleteTask(context.Context, *CompleteTaskRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedDataPushCallbackServiceServer()
}

// UnimplementedDataPushCallbackServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataPushCallbackServiceServer struct{}

func (UnimplementedDataPushCallbackServiceServer) CompleteTask(context.Context, *CompleteTaskRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteTask not implemented")
}
func (UnimplementedDataPushCallbackServiceServer) mustEmbedUnimplementedDataPushCallbackServiceServer() {
}
func (UnimplementedDataPushCallbackServiceServer) testEmbeddedByValue() {}

// UnsafeDataPushCallbackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataPushCallbackServiceServer will
// result in compilation errors.
type UnsafeDataPushCallbackServiceServer interface {
	mustEmbedUnimplementedDataPushCallbackServiceServer()
}

func RegisterDataPushCallbackServiceServer(s grpc.ServiceRegistrar, srv DataPushCallbackServiceServer) {
	// If the following call pancis, it indicates UnimplementedDataPushCallbackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataPushCallbackService_ServiceDesc, srv)
}

func _DataPushCallbackService_CompleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataPushCallbackServiceServer).CompleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataPushCallbackService_CompleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataPushCallbackServiceServer).CompleteTask(ctx, req.(*CompleteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataPushCallbackService_ServiceDesc is the grpc.ServiceDesc for DataPushCallbackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataPushCallbackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "data_catalog.v1.DataPushCallbackService",
	HandlerType: (*DataPushCallbackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CompleteTask",
			Handler:    _DataPushCallbackService_CompleteTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data_push.proto",
}
