// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: service.proto

package register

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyncFlag      string                 `protobuf:"bytes,1,opt,name=sync_flag,json=syncFlag,proto3" json:"sync_flag,omitempty"` //同步状态(success,fail)
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`                           //返回消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *Result) GetSyncFlag() string {
	if x != nil {
		return x.SyncFlag
	}
	return ""
}

func (x *Result) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaasId        string                 `protobuf:"bytes,1,opt,name=paas_id,json=paasId,proto3" json:"paas_id,omitempty"`                         //网关注册id，对应AF应用ID
	SvcId         string                 `protobuf:"bytes,2,opt,name=svc_id,json=svcId,proto3" json:"svc_id,omitempty"`                            //服务id，对应AF接口服务ID
	SvcName       string                 `protobuf:"bytes,3,opt,name=svc_name,json=svcName,proto3" json:"svc_name,omitempty"`                      //服务名，对应AF接口服务名
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                             //服务描述，对应AF接口服务描述
	PubHost       string                 `protobuf:"bytes,5,opt,name=pub_host,json=pubHost,proto3" json:"pub_host,omitempty"`                      //网关公共域名，留空
	PubPath       string                 `protobuf:"bytes,6,opt,name=pub_path,json=pubPath,proto3" json:"pub_path,omitempty"`                      //网关公共路径，留空
	TargetPath    string                 `protobuf:"bytes,7,opt,name=target_path,json=targetPath,proto3" json:"target_path,omitempty"`             //网关目标路径，由AF接口服务路径拼接而成(/{固定前缀ebus}/{paas_id}/{接口路径服务路径})
	TargetIsHttps bool                   `protobuf:"varint,8,opt,name=target_is_https,json=targetIsHttps,proto3" json:"target_is_https,omitempty"` //接口uri是否https
	SvcCode       string                 `protobuf:"bytes,9,opt,name=svc_code,json=svcCode,proto3" json:"svc_code,omitempty"`                      //服务code
	IsOldSvc      bool                   `protobuf:"varint,10,opt,name=is_old_svc,json=isOldSvc,proto3" json:"is_old_svc,omitempty"`               // 是否为老的服务
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequest) GetPaasId() string {
	if x != nil {
		return x.PaasId
	}
	return ""
}

func (x *CreateRequest) GetSvcId() string {
	if x != nil {
		return x.SvcId
	}
	return ""
}

func (x *CreateRequest) GetSvcName() string {
	if x != nil {
		return x.SvcName
	}
	return ""
}

func (x *CreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRequest) GetPubHost() string {
	if x != nil {
		return x.PubHost
	}
	return ""
}

func (x *CreateRequest) GetPubPath() string {
	if x != nil {
		return x.PubPath
	}
	return ""
}

func (x *CreateRequest) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

func (x *CreateRequest) GetTargetIsHttps() bool {
	if x != nil {
		return x.TargetIsHttps
	}
	return false
}

func (x *CreateRequest) GetSvcCode() string {
	if x != nil {
		return x.SvcCode
	}
	return ""
}

func (x *CreateRequest) GetIsOldSvc() bool {
	if x != nil {
		return x.IsOldSvc
	}
	return false
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaasId        string                 `protobuf:"bytes,1,opt,name=paas_id,json=paasId,proto3" json:"paas_id,omitempty"`                         //网关注册id，对应AF应用ID
	SvcId         string                 `protobuf:"bytes,2,opt,name=svc_id,json=svcId,proto3" json:"svc_id,omitempty"`                            //服务id，对应AF接口服务ID
	SvcName       string                 `protobuf:"bytes,3,opt,name=svc_name,json=svcName,proto3" json:"svc_name,omitempty"`                      //服务名，对应AF接口服务名
	PubHost       string                 `protobuf:"bytes,4,opt,name=pub_host,json=pubHost,proto3" json:"pub_host,omitempty"`                      //网关公共域名，留空
	PubPath       string                 `protobuf:"bytes,5,opt,name=pub_path,json=pubPath,proto3" json:"pub_path,omitempty"`                      //网关公共路径，留空
	TargetPath    string                 `protobuf:"bytes,6,opt,name=target_path,json=targetPath,proto3" json:"target_path,omitempty"`             //网关目标路径，由AF接口服务路径拼接而成(/{固定前缀ebus}/{paas_id}/{接口路径服务路径})
	TargetIsHttps bool                   `protobuf:"varint,7,opt,name=target_is_https,json=targetIsHttps,proto3" json:"target_is_https,omitempty"` //接口uri是否https
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`                             //服务描述，对应AF接口服务描述
	SvcCode       string                 `protobuf:"bytes,9,opt,name=svc_code,json=svcCode,proto3" json:"svc_code,omitempty"`                      //服务code
	IsOldSvc      bool                   `protobuf:"varint,10,opt,name=is_old_svc,json=isOldSvc,proto3" json:"is_old_svc,omitempty"`               // 是否为老的服务
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRequest) GetPaasId() string {
	if x != nil {
		return x.PaasId
	}
	return ""
}

func (x *UpdateRequest) GetSvcId() string {
	if x != nil {
		return x.SvcId
	}
	return ""
}

func (x *UpdateRequest) GetSvcName() string {
	if x != nil {
		return x.SvcName
	}
	return ""
}

func (x *UpdateRequest) GetPubHost() string {
	if x != nil {
		return x.PubHost
	}
	return ""
}

func (x *UpdateRequest) GetPubPath() string {
	if x != nil {
		return x.PubPath
	}
	return ""
}

func (x *UpdateRequest) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

func (x *UpdateRequest) GetTargetIsHttps() bool {
	if x != nil {
		return x.TargetIsHttps
	}
	return false
}

func (x *UpdateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateRequest) GetSvcCode() string {
	if x != nil {
		return x.SvcCode
	}
	return ""
}

func (x *UpdateRequest) GetIsOldSvc() bool {
	if x != nil {
		return x.IsOldSvc
	}
	return false
}

type StatusUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaasId        string                 `protobuf:"bytes,1,opt,name=paas_id,json=paasId,proto3" json:"paas_id,omitempty"`          //网关注册id，对应AF应用ID
	SvcId         string                 `protobuf:"bytes,2,opt,name=svc_id,json=svcId,proto3" json:"svc_id,omitempty"`             //服务id，对应AF接口服务ID
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                        //状态，对应AF接口服务的状态（下线0上线1）
	SvcCode       string                 `protobuf:"bytes,4,opt,name=svc_code,json=svcCode,proto3" json:"svc_code,omitempty"`       //服务code
	IsOldSvc      bool                   `protobuf:"varint,5,opt,name=is_old_svc,json=isOldSvc,proto3" json:"is_old_svc,omitempty"` // 是否为老的服务
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusUpdateRequest) Reset() {
	*x = StatusUpdateRequest{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUpdateRequest) ProtoMessage() {}

func (x *StatusUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUpdateRequest.ProtoReflect.Descriptor instead.
func (*StatusUpdateRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *StatusUpdateRequest) GetPaasId() string {
	if x != nil {
		return x.PaasId
	}
	return ""
}

func (x *StatusUpdateRequest) GetSvcId() string {
	if x != nil {
		return x.SvcId
	}
	return ""
}

func (x *StatusUpdateRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusUpdateRequest) GetSvcCode() string {
	if x != nil {
		return x.SvcCode
	}
	return ""
}

func (x *StatusUpdateRequest) GetIsOldSvc() bool {
	if x != nil {
		return x.IsOldSvc
	}
	return false
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\bregister\"7\n" +
	"\x06Result\x12\x1b\n" +
	"\tsync_flag\x18\x01 \x01(\tR\bsyncFlag\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\xb4\x02\n" +
	"\rCreateRequest\x12\x17\n" +
	"\apaas_id\x18\x01 \x01(\tR\x06paasId\x12\x15\n" +
	"\x06svc_id\x18\x02 \x01(\tR\x05svcId\x12\x19\n" +
	"\bsvc_name\x18\x03 \x01(\tR\asvcName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x19\n" +
	"\bpub_host\x18\x05 \x01(\tR\apubHost\x12\x19\n" +
	"\bpub_path\x18\x06 \x01(\tR\apubPath\x12\x1f\n" +
	"\vtarget_path\x18\a \x01(\tR\n" +
	"targetPath\x12&\n" +
	"\x0ftarget_is_https\x18\b \x01(\bR\rtargetIsHttps\x12\x19\n" +
	"\bsvc_code\x18\t \x01(\tR\asvcCode\x12\x1c\n" +
	"\n" +
	"is_old_svc\x18\n" +
	" \x01(\bR\bisOldSvc\"\xb4\x02\n" +
	"\rUpdateRequest\x12\x17\n" +
	"\apaas_id\x18\x01 \x01(\tR\x06paasId\x12\x15\n" +
	"\x06svc_id\x18\x02 \x01(\tR\x05svcId\x12\x19\n" +
	"\bsvc_name\x18\x03 \x01(\tR\asvcName\x12\x19\n" +
	"\bpub_host\x18\x04 \x01(\tR\apubHost\x12\x19\n" +
	"\bpub_path\x18\x05 \x01(\tR\apubPath\x12\x1f\n" +
	"\vtarget_path\x18\x06 \x01(\tR\n" +
	"targetPath\x12&\n" +
	"\x0ftarget_is_https\x18\a \x01(\bR\rtargetIsHttps\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x19\n" +
	"\bsvc_code\x18\t \x01(\tR\asvcCode\x12\x1c\n" +
	"\n" +
	"is_old_svc\x18\n" +
	" \x01(\bR\bisOldSvc\"\x96\x01\n" +
	"\x13StatusUpdateRequest\x12\x17\n" +
	"\apaas_id\x18\x01 \x01(\tR\x06paasId\x12\x15\n" +
	"\x06svc_id\x18\x02 \x01(\tR\x05svcId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x19\n" +
	"\bsvc_code\x18\x04 \x01(\tR\asvcCode\x12\x1c\n" +
	"\n" +
	"is_old_svc\x18\x05 \x01(\bR\bisOldSvc2\xbe\x01\n" +
	"\vUserService\x125\n" +
	"\x06Create\x12\x17.register.CreateRequest\x1a\x10.register.Result\"\x00\x125\n" +
	"\x06Update\x12\x17.register.UpdateRequest\x1a\x10.register.Result\"\x00\x12A\n" +
	"\fStatusUpdate\x12\x1d.register.StatusUpdateRequest\x1a\x10.register.Result\"\x00B`Z^github.com/kweaver-ai/idrm-go-common/callback/data_application_service/registerb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP([]byte(file_service_proto_rawDesc))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_service_proto_goTypes = []any{
	(*Result)(nil),              // 0: register.Result
	(*CreateRequest)(nil),       // 1: register.CreateRequest
	(*UpdateRequest)(nil),       // 2: register.UpdateRequest
	(*StatusUpdateRequest)(nil), // 3: register.StatusUpdateRequest
}
var file_service_proto_depIdxs = []int32{
	1, // 0: register.UserService.Create:input_type -> register.CreateRequest
	2, // 1: register.UserService.Update:input_type -> register.UpdateRequest
	3, // 2: register.UserService.StatusUpdate:input_type -> register.StatusUpdateRequest
	0, // 3: register.UserService.Create:output_type -> register.Result
	0, // 4: register.UserService.Update:output_type -> register.Result
	0, // 5: register.UserService.StatusUpdate:output_type -> register.Result
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: []byte(file_service_proto_rawDesc),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
