// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: work_order.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkOrderCallbackService_OnApproved_FullMethodName = "/task_center.v1.WorkOrderCallbackService/OnApproved"
)

// WorkOrderCallbackServiceClient is the client API for WorkOrderCallbackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 工单回调服务接口（由集成开发实现）
type WorkOrderCallbackServiceClient interface {
	// 工单通过审批
	OnApproved(ctx context.Context, in *WorkOrderApprovedEvent, opts ...grpc.CallOption) (*CommonResult, error)
}

type workOrderCallbackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkOrderCallbackServiceClient(cc grpc.ClientConnInterface) WorkOrderCallbackServiceClient {
	return &workOrderCallbackServiceClient{cc}
}

func (c *workOrderCallbackServiceClient) OnApproved(ctx context.Context, in *WorkOrderApprovedEvent, opts ...grpc.CallOption) (*CommonResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResult)
	err := c.cc.Invoke(ctx, WorkOrderCallbackService_OnApproved_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkOrderCallbackServiceServer is the server API for WorkOrderCallbackService service.
// All implementations must embed UnimplementedWorkOrderCallbackServiceServer
// for forward compatibility.
//
// 工单回调服务接口（由集成开发实现）
type WorkOrderCallbackServiceServer interface {
	// 工单通过审批
	OnApproved(context.Context, *WorkOrderApprovedEvent) (*CommonResult, error)
	mustEmbedUnimplementedWorkOrderCallbackServiceServer()
}

// UnimplementedWorkOrderCallbackServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkOrderCallbackServiceServer struct{}

func (UnimplementedWorkOrderCallbackServiceServer) OnApproved(context.Context, *WorkOrderApprovedEvent) (*CommonResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnApproved not implemented")
}
func (UnimplementedWorkOrderCallbackServiceServer) mustEmbedUnimplementedWorkOrderCallbackServiceServer() {
}
func (UnimplementedWorkOrderCallbackServiceServer) testEmbeddedByValue() {}

// UnsafeWorkOrderCallbackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkOrderCallbackServiceServer will
// result in compilation errors.
type UnsafeWorkOrderCallbackServiceServer interface {
	mustEmbedUnimplementedWorkOrderCallbackServiceServer()
}

func RegisterWorkOrderCallbackServiceServer(s grpc.ServiceRegistrar, srv WorkOrderCallbackServiceServer) {
	// If the following call pancis, it indicates UnimplementedWorkOrderCallbackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkOrderCallbackService_ServiceDesc, srv)
}

func _WorkOrderCallbackService_OnApproved_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkOrderApprovedEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkOrderCallbackServiceServer).OnApproved(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkOrderCallbackService_OnApproved_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkOrderCallbackServiceServer).OnApproved(ctx, req.(*WorkOrderApprovedEvent))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkOrderCallbackService_ServiceDesc is the grpc.ServiceDesc for WorkOrderCallbackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkOrderCallbackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "task_center.v1.WorkOrderCallbackService",
	HandlerType: (*WorkOrderCallbackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnApproved",
			Handler:    _WorkOrderCallbackService_OnApproved_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "work_order.proto",
}
